### PR TITLE
docs: add MES on showcase

### PR DESCRIPTION
**Pull request by hkd987**
# What is it?
We recently rewrote the https://meetenhancementsuite.com/ landing page to be a SSR Qwik application, and would love to showcase it. 

- [ ] Feature / enhancement
- [ ] Bug
- [X] Docs / tests

# Description
We worked for the past two weeks to convert on Ruby on Rails Jekyl site into a Qwik site and would love to showcase that to other Qwik community members.

### CODE REVIEW

**Comment by manucorporat** [comment]
The speed score is not very good though:
https://pagespeed.web.dev/report?url=https%3A%2F%2Fmeetenhancementsuite.com%2F

Seems like the perf drop is caused by:
- images not having a specified width/height (which causes layout invalidation)
- google analytics and other lib

Are you aware of partytown?

**Comment by hkd987** [comment]
Thats pretty odd since Lighthouse gives this website a 98....🤔

**Comment by zanettin** [comment]
Hi @hkd987 👋 
Just wanted to quickly check-in and ask if you had a chance to implement partytown on your app as suggested by Manu? The showcases show always the mobile scores and they are on your page at 73 currently. Desktop is at 97 which is great 😄

**Comment by zanettin** [comment]
Hi @hkd987 👋 
Just re-checked the page and it looks like the mobile score didn't change since the last review. Would be great if you could try to improve the scores as mentioned by Manu above 🙏  my suggestion would be to keep this PR open for 2 more weeks and close it then. Feel free to create a new one when ever you're ready 🎉

**Comment by zanettin** [comment]
Hi @hkd987 👋 
Thanks again for creating this PR and submitting your page 🙏 since i didn't hear anything from you i'll close this PR for now. Feel free to re-open it at any time when u think the page is ready.

**Pull request closed without merging**
