### PR TITLE
refactor: tidy up quik/core

### PR DESCRIPTION
**Pull request by Simon-He95**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by Simon-He95** [comment]
@manucorporat I have done it, pls check :)

**Comment by manucorporat** [comment]
it's breaking the unit tests, some of the changes are not equivalent, specially the typeof document, or typeof window

**Comment by Simon-He95** [comment]
typeof document !== 'undefined', wrapped with the function will fail the unit test. I don't know why. I have changed back with typeof

**Comment by zanettin** [comment]
Hi @Simon-He95 
Thanks for this PR 🙏  @manucorporat are this changes something you want to have and @Simon-He95 can you have a look at the conflicts? 👼

**Comment by Simon-He95** [comment]
> Hi @Simon-He95 Thanks for this PR 🙏 @manucorporat are this changes something you want to have and @Simon-He95 can you have a look at the conflicts? 👼

of course, I have done

**Comment by zanettin** [comment]
Thanks for the adjustmets @Simon-He95 🙏  Looks like the CI is still "not amused" 🙈 may i ask u to have another look at it? 🙏

**Comment by Simon-He95** [comment]
> Thanks for the adjustmets @Simon-He95 🙏 Looks like the CI is still "not amused" 🙈 may i ask u to have another look at it? 🙏

I have fixed it and now the CI is passed

**Comment by manucorporat** [comment]
I am a little against this change, because i dont see much value on it, and it can introduce unwanted effects, Qwik does not have an integrate benchmark suite, and some of this changes are in hot loops, because some of this values are polymorphics, i fear that V8 will not be able to inline the calls to this functions, and introduce an overhead. In addition, i dont see it saving much space of making the code clear. `isObject` is the only so far, i like.

**Pull request closed without merging**
