### PR TITLE
feat: worker$ in qwikcity

### PR DESCRIPTION
**Pull request by manucorporat**
worker$() is not longer experimental!

### CODE REVIEW

**Comment by mrhoodz** [comment]
worker$
This could be handy.

**Comment by mrhoodz** [comment]
@manucorporat
Seems like its not in main yet ?😥

**Comment by 7x7cl** [comment]
any update for this? $worker not export by qwik-city

**Comment by hamatoyogi** [comment]
This was added as a package inside Qwik repo in the end:
https://www.npmjs.com/package/@builder.io/qwik-worker

**Pull request closed without merging**
