### PR TITLE
refactor: ship latest API stabilizations

### PR DESCRIPTION
**Pull request by manucorporat**
# Breaking changes

- `useScopedStyles()` -> `useStylesScoped()`
- `useWatch$((track) => {})` -> `useWatch$(({track}) => {})`
- `useClientEffect$((track) => {})` -> `useClientEffect$(({track}) => {})`
- `useServerMount$(): Resource<>` -> `useServerMount$(): void`
- `useMount$(): Resource<>` -> `useMount$(): void`

### CODE REVIEW

**Comment by shairez** [comment]
Thanks Manu!

One issue that I forgot to mention yesterday - what's the difference between `useWatch` and `useClientEffect` ?

I'm guessing `useCLientEffect$` is running only on the client... but why should we use `useWatch` then?

**Comment by manucorporat** [comment]
useWatch runs before the render, and can run in both places server and client. In the client it never runs eagerly.

We might need more docs about this

**Comment by shairez** [comment]
Thanks! 

If that's the case, I think it might be less confusing to call it something similar to useClientEffect - like... `useEffect` ... or to change `useClientEffect` to `useClientWatch` to match them 

Does it make sense?

**Comment by manucorporat** [comment]
This API has went through a lot of renamed in fact;
useWatchEffect,
useEffect, and finally useClientEffect.

We want to tag as client or server APIs that only run on those platforms, for now only `useClientEffect` and `useServerMount`.

useEffect would conflict with useEffect semantics in React, and that was also a reason to avoid that name.

**Comment by manucorporat** [comment]
Also, watch and effect has different semantics:
- effect: after render
- watch: on data change before render (giving a better time for updating data before render)

**Pull request merged**
