### PR TITLE
chore: change `useUserContext` to `useEnvData`

### PR DESCRIPTION
**Pull request by shairez**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

Following our discussion, we decided that `useEnvData` is a more descriptive name than `useUserContext` and might cause less confusions in the future. 

This is a BREAKING CHANGE (why am I yelling? 😅)
but for an undocumented api which only qwik city uses at the moment

# Checklist:

- [x] My code follows the [developer guidelines of this project](../CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by manucorporat** [comment]
RenderOptions should be updated too, it still has userContext there

**Comment by shairez** [comment]
@manucorporat done!
(plus I changed `userCtx` as well)

**Comment by manucorporat** [comment]
looking great! lets wait for the CI to pass and merge it

**Comment by manucorporat** [comment]
This breaking change is tricky, because it's self referenced, qwikcity needs a version that is not released

**Pull request merged**
