### PR TITLE
fix(core): Added StringSerializer for strings that start with the prefixes of serializers.

### PR DESCRIPTION
**Pull request by genki**
In order to solve the issue #5175 
added `NOSERIALIZE_PREFIX` to mark the binary strings that are not serialized

# Overview

# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests / types / typos

# Description

The Qwik serializer had treated all strings as possibly serialized and try to resume them even for binary strings that start with prefixes for serializer.
So I introduced the `NOSERIALIZE_PREFIX` to mark the binary strings so that the Qwik serializer can distinguish they don't need to be deserialized.

# Use cases and why

We can use binary strings correctly.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Review by mhevery — CHANGES_REQUESTED** [review]
If I understand this PR correctly all strings will now get a special prefix.... I think this will bloat the output....

I think a better approach is to create a new serializer that will trigger on strings that start with a special character and only then on the serialization prefix. This way we are not polluting all of the existing strings in the serialization.

Do you think you could take on that?

**Comment by genki** [comment]
@mhevery I see, I will try :)

**Comment by genki** [comment]
I introduced the `StringSerializer` that serializes strings of which start with the prefixes of serializers.
Other normal strings are stay being themselves.

**Comment by mhevery** [comment]
Thanks for the contribution. I did some "minor" cleanup...

**Review by mhevery — APPROVED** [review]

**Comment by genki** [comment]
@mhevery Thanks a lot :)

**Comment by genki** [comment]
Failed on E2E Tests? Hmm...

**Comment by genki** [comment]
I have confirmed the E2E test `pnpm run test.e2e.chromium` at my local environment.

At 5d85187970d0e0d5b611f73a942c7509af2e0dc0 Passed
At d25968e638aa4b0612893254ac89986f96e9a9b4 Passed
At 4c90bf0fab95133d225bb837bfa943b27bb303c4 Failed

@mhevery Could you confirm it?

**Comment by genki** [comment]
Found a issue in the `serializeObjects` so fixed it.
Now the StringSerializer tests the `UNDEFINED_PREFIX` as it must be serialized as special character.

**Comment by genki** [comment]
Now passed the E2E test :)
But it still fails on the treeshaking of the `core.min.mjs`

**Comment by genki** [comment]
Now all tests have passed.
@mhevery Could you confirm?

**Review by mhevery — APPROVED** [review]

**Pull request merged**
