### PR TITLE
docs: pnpm contributors

### PR DESCRIPTION
**Pull request by AmirSa12**
# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by AmirSa12** [comment]
this script should get executed manually as it's not automated yet. 
So, the maintainers/contributors should run this script to keep the frontmatter of the docs updated. we are finding a way to make this script automatically executed.

**Review by gioboa — CHANGES_REQUESTED** [review]
Thanks @AmirSa12 
I have one concern, now you are in all the files even if you didn't change them all I guess
Can you verify this behaviour?

**Comment by AmirSa12** [comment]
> Thanks @AmirSa12 
> 
> I have one concern, now you are in all the files even if you didn't change them all I guess
> 
> Can you verify this behaviour?

Yes I didn't change all of them, but I think it's because of the rebase, I'm in all the old doc's files. Not the new docs which were recently added after the rebase. I'm still not sure if it's really because the rebase, but I think it's the reason the script adds me.

**Comment by gioboa** [comment]
I would like to have a review from a core team member b/c change these file over and over with a PR is not a good thing to me. A specific GitHub action for this work seems better.

**Comment by AmirSa12** [comment]
> I would like to have a review from a core team member b/c change these file over and over with a PR is not a good thing to me. A specific GitHub action for this work seems better.

I totally agree, I've told @mhevery about this case and  the GHA idea, and a friend and I are still working on it.

**Comment by gioboa** [comment]
Ok, so I think better thing to do is close this one and wait for the GitHub action one.

**Comment by PatrickJS** [comment]
closing this because of this https://github.com/BuilderIO/qwik/pull/5633#issuecomment-1869442122 comment. If you think this should be open feel free to open the PR again

**Pull request closed without merging**
