### PR TITLE
docs: add Wope to showcase

### PR DESCRIPTION
**Pull request by necatikcl**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

Hello there, we've written our landing page, https://wope.com/ in Qwik.js and proud of the results we've gotten a perfect performance score (most of time, though). We would love to show it in the showcase on Qwik docs. :)

https://twitter.com/i/status/1621301824090259462

### CODE REVIEW

**Comment by manucorporat** [comment]
This is amazing!! one of the most beautiful landing pages i have ever seen! even if i didnt know what it does, i would love to use it OMG! in fact going to try it!

The site achieves a perfect score of 100 in desktop but in the showcase we show the MOBILE one:
https://pagespeed.web.dev/report?url=https%3A%2F%2Fwope.com%2F
Screenshot 2023-02-03 at 13 11 10


I have been looking into it, and i can see that your target is most likely using the desktop and most of the landing page is better enjoyed from a desktop!

So, i propose that in mobile, you dont run that many animations, specially the video at the top!
that should get u to a perfect score in Mobile, also the font in mobile, you could skip it

Thoughts?

**Comment by necatikcl** [comment]
Thank you! I thought the docs show the desktop versions so I couldn't wait to open a PR :) Our mobile version is not yet ready, but we're working on it; I will leave a comment here when it is ready :)

**Comment by manucorporat** [comment]
Amazing! yeah might be confusing! we show the Mobile Pagespeed! which is even more impressive, please let me know when it's ready and/or how i can help!

**Comment by necatikcl** [comment]
The mobile version is almost ready but the test results are quite interesting 🤔 In PageSpeed Insights website, Wope gets 85-90~ but when I test it in either API, Lighthouse or the NPM package, it gets at least 95 and average of 98 🤔 

Any ideas? @manucorporat

**Comment by zanettin** [comment]
Hi @necatikcl 
Very nice that you have been able to work on the mobile page as well. I am now also getting scores in the range you mentioned 🎉 

regarding your question of what could be optimized i just found this: 
the `hero-background.png` could be provided as `webp` and/or `avif` version (https://squoosh.app/). this should save about 90% of the file size and increase the LCP. another thing to analyze could be the TBT which is high. i am not sure after having just a quick look what exactly block the main thread. maybe you find smth which can be deferred or removed for the mobile version.

hope this helps.

@manucorporat my suggestion would be to merge this PR. a score of 87 (locally 95) should be ok, right? 😄

**Comment by necatikcl** [comment]
I already spent over a week to deep analyse the mobile cons :D Images are minified using tinypng (which reduced their size by 90%~~) I already tested AVIF and WEBP versions but they are slightly bigger than tinypng in terms of size. 

Thank you for your advices though ^^

**Comment by zanettin** [comment]
uh good that you've already tried that 👍 😄  
i downloaded [this img](https://wope.com/images/hero/mobile/hero-background.png) yesterday which has 116kb in size and run it through squoosh which gave me an image at the size of at about 8.5kb. are these 116kb already compressed? because when i run it again through tinypng i just get a reduction of 2% 😄

**Comment by zanettin** [comment]
yes i see 😃 always a compromise, right 😄

**Comment by zanettin** [comment]
Bildschirmfoto 2023-03-09 um 16 48 08
PSI is happy now as well with 97 on mobile 🎉 
gonna close and re-open this PR quickly to trigger CI again

**Pull request merged**
