### PR TITLE
feat: complex form data

### LINKED ISSUE #3183: [✨] Support complex nested forms
### Is your feature request related to a problem?

As of Qwik 0.19.3 there isn't a way to submit and validate complex nested form data as seen below.

```js
export const useAction = globalAction$(
  async (formData, ctx) => {
    console.log(formData);
    /*
    {
      todo: [
        { title: 'Wash clothes' },
        { title: 'Buy Food', desc: 'Apple, banana' },
      ];
    }
    */
  },
  zod$({
    todo: z.array(
      z.object({
        title: z.string(),
        desc: z.string().optional(),
      }),
    ),
  }),
);
```

### Describe the solution you'd like

```tsx
{[
  { title: 'Wash clothes' },
  { title: 'Buy Food', desc: 'Apple, banana' },
].map((todo, i) => {
  <>
    <input type="text" name={`todo.${i}.title`} value={todo.title} />
    <input type="text" name={`todo.${i}.desc`} value={todo.desc} />
  </>;
})}
```

### Describe alternatives you've considered

```tsx
{[
  { title: 'Wash clothes' },
  { title: 'Buy Food', desc: 'Apple, banana' },
].map((todo, i) => {
  <>
    <input type="text" name={`todo[${i}].title`} value={todo.title} />
    <input type="text" name={`todo[${i}].desc`} value={todo.desc} />
  </>;
})}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ulic75**
# Overview

Adds support for converting formdata into complex objects and arrays, including arrays of objects.  Thank you @fabian-hiller for your ModularForms which I based the code on.

Closes #3183 

# What is it?

- [x] Feature / enhancement
- [x] Docs / tests / types / typos

# Description

Rewrote the formToObj function to support arrays of objects in addition to everything it supported before (objects, and simple arrays using []).

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by ulic75** [comment]
Looking into the failing tests.

**Comment by manucorporat** [comment]
Happy to merge this soon! amazing job

**Comment by tzdesign** [comment]
@ulic75 you don't know how many lines of code we can remove in our project.

Thank you so much 

image

**Comment by tzdesign** [comment]
@manucorporat is this something we will see in one of the next releases?

**Review by mhevery — APPROVED** [review]

**Comment by tzdesign** [comment]
@ulic75 I start implementing it with a e-commerce cart.

If I have a zodSchema like this:
```ts
export const addressSchema = z.object({
  company: z.string().optional(),
  workTitle: z.string().optional(),
  title: titleSchema.optional(),
  salutation: salutationSchema.optional(),
  firstname: z.string().min(2),
  lastname: z.string().min(2),
  street: z.string().min(2),
  streetNumber: z.string().min(1),
  zip: z.string().min(2),
  city: z.string().min(2),
  country: z.string().min(2),
  phone: z.string().optional(),
  mobile: z.string().optional(),
  fax: z.string().optional(),
  email: emailSchema.optional()
});
```
The errors I get back are not referenceable:
image

Zod knows the path:
image

Is it possible to implement the path here as well? This way you need a custom message for everything and flatten the arrays, but this will be a lot of work with multiple schemas.

**Comment by tzdesign** [comment]
@ulic75 ah, manu is just outputting ```error.flatten``` here.

I will check if I can fix it myself next week. If the default zodError always has a path, I would just join the path and we will end up with your dot notation.

**Comment by ulic75** [comment]
Thought it sounded more zod related.  Sounds like a good thing to PR a fix for though.

**Comment by tzdesign** [comment]
@ulic75 I think a qwik reduce like this would be good:
```tsx
  const errorByPath: Record<string, string> = result.error.issues.reduce(
    (acc, issue) => ({ ...acc, [issue.path.join('.')]: issue.message }),
    {} satisfies Record<string, string>
  );

```
I can't figure out how to put it in the DataValidator type yet. But when I have time next week, I will take a look.

**Comment by tzdesign** [comment]
@ulic75 Can you find your way around the action types? We have a complex cart type with addresses etc. and if cart.invoiceAddress.firstName fails, then you no longer know which field within cart has failed. The errors are flatten inside of cart.

```ts
cart: string[]
```

**Pull request merged**
