### PR TITLE
fix: externalize node:async_hooks for all adapters

### PR DESCRIPTION
**Pull request by wmertens**

### CODE REVIEW

**Review by gioboa — APPROVED** [review]

**Comment by brandonpittman** [comment]
Just updated to 1.5.0 and getting an error around async_hooks.

```
[commonjs--resolver] Cannot bundle Node.js built-in "node:async_hooks" imported from "../../node_modules/@builder.io/qwik-city/middleware/request-handler/index.mjs". Consider disabling ssr.noExternal or remove the built-in dependency.
error during build:
RollupError: Cannot bundle Node.js built-in "node:async_hooks" imported from "../../node_modules/@builder.io/qwik-city/middleware/request-handler/index.mjs". Consider disabling ssr.noExternal or remove the built-in dependency.
    at error (file:///XXX/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Object.error (file:///XXX/node_modules/rollup/dist/es/shared/node-entry.js:25351:20)
    at Object.resolveId (file:///XXX/node_modules/vite/dist/node/chunks/dep-52909643.js:28225:34)
    at Object.handler (file:///XXX/node_modules/vite/dist/node/chunks/dep-52909643.js:48308:19)
    at file:///XXX/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///XXX/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)
    at async resolveId (file:///XXX/node_modules/rollup/dist/es/shared/node-entry.js:24117:26)
    at async ModuleLoader.resolveId (file:///XXX/node_modules/rollup/dist/es/shared/node-entry.js:24531:15)
    at async Object.resolveId (file:///XXX/node_modules/vite/dist/node/chunks/dep-52909643.js:7910:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///XXX/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)
```

Something different than this?

**Comment by VinSpee** [comment]
Hi! After upgrading to 1.5.0, I'm getting this error building for production (vercel adapter if it's helpful)

```
RollupError: [commonjs--resolver] Cannot bundle Node.js built-in "node:async_hooks" imported from "node_modules/.pnpm/@builder.io+qwik-city@1.5.0_@types+node@20.11.24/node_modules/@builder.io/qwik-city/middleware/request-handler/index.mjs". Consider disabling ssr.noExternal or remove the built-in dependency.
```

feels related.

**Comment by wmertens** [comment]
Hi all, you need to add node:async_hooks to your externals. I'll add a comment to the release.

**Comment by brandonpittman** [comment]
Even after adding that to vite.config.ts, I'm still getting this error when building for production.

https://github.com/BuilderIO/qwik/pull/5908#issuecomment-1978125280

**Comment by wmertens** [comment]
@brandonpittman can you share your configuration? It should be impossible for you to get that error

**Comment by brandonpittman** [comment]
@wmertens 

```ts
import { defineConfig } from "vite";
import { qwikVite } from "@builder.io/qwik/optimizer";
import { qwikCity } from "@builder.io/qwik-city/vite";
import tsconfigPaths from "vite-tsconfig-paths";
import { vanillaExtractPlugin } from "styled-vanilla-extract/vite";
import { qwikTypes } from "@builder.io/qwik-labs/vite";

export default defineConfig(() => {
  return {
    define: {
      // enables debugging in workbox
      "process.env.NODE_ENV": JSON.stringify("development"),
    },
    plugins: [
      qwikCity(),
      qwikVite(),
      tsconfigPaths(),
      qwikTypes(),
      vanillaExtractPlugin(),
    ],
    preview: {
      headers: {
        "Cache-Control": "public, max-age=600",
      },
    },
  };
});
```

Here's my Vite config. Nothing crazy.

**Comment by wmertens** [comment]
Actually I just realized I can define the externals in the qwikVite plugin :facepalm:. I'm doing that now and will release qwik@dev with this change shortly.

**Comment by wmertens** [comment]
@brandonpittman can you upgrade to qwik@dev? That should fix the production build without further changes

**Comment by wmertens** [comment]
Actually it works fine in test projects for me, so I'm deploying 1.5.1.

**Comment by brandonpittman** [comment]
Ah, it's having a problem in the Cloudflare `vite.config.ts`.

**Comment by brandonpittman** [comment]
@wmertens 

I figured out the problem: Vite 4. I started this app before Vite 5 was released and it was working fine up till now. I created a new app and compared the `package.json` and found that my Vite at 4 while the fresh one was 5. Probably could use a mention in the release notes.

**Comment by wmertens** [comment]
@brandonpittman so you're using 1.5.1 and iets still broken, and you upgraded to vite 5 and it works?

**Comment by brandonpittman** [comment]
1.5.1 with Vite 4 is broken.

1.5.1 with Vite 5 is fine.

**Pull request merged**
