### PR TITLE
feat(docs): add basic docs for the auth plugin

### PR DESCRIPTION
**Pull request by ulic75**

### CODE REVIEW

**Comment by zanettin** [comment]
thanks a lot @ulic75 🙏  ready to merge?

**Comment by ulic75** [comment]
> thanks a lot @ulic75 🙏 ready to merge?

I think we should wait for the next release cycle as there were something things broken in starter that have been fixed.

**Comment by zanettin** [comment]
Hi @ulic75 👋 
Release of `0.21.1` just went out 🎉  ready to merge?

**Comment by ulic75** [comment]
I was waiting until the integration was working correctly.  My first attempt didn't inject into the vite.config at all.  Hopefully #3295 resolves it.  I personally think we should wait to push the docs until at least the basic install is working correctly, the docs have enough issues with being out of sync and I'd rather not add to it :)

Also haven't seen 0.21.1 yet, just 0.21.0.

**Comment by zanettin** [comment]
All good @ulic75 😄  leave it up 2 u of corse 👍 just let me (or anybody else) know when you think it is ready 👍 
and sry for the typo. yes of corse it is `0.21.0` 🙈 😄

**Comment by ulic75** [comment]
@zanettin I'm not sure what all you can merge or not.  I also know you have some familiarity with the cli.  Maybe you could take a look at #3295 and see if it looks correct and get it merged?  It would be nice to have this working, get some docs out there and have people beat on this in case there are any issue.

**Comment by zanettin** [comment]
Hi @ulic75 👋  checking the pkgs changes now. getting back to u asap 👍

**Comment by ulic75** [comment]
I made a mess of this PR trying to update it for the "ecosystem" change.  I think I'll close it and create a new one.

**Pull request closed without merging**
