### PR TITLE
docs(course): qwik course spanish by Fernando Herrera

### PR DESCRIPTION
**Pull request by leifermendez**
# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by manucorporat** [comment]
lint failing :)

**Comment by leifermendez** [comment]
> lint failing :)

I'll fix it

**Comment by leifermendez** [comment]
done @manucorporat

**Comment by manucorporat** [comment]
Hey man! Fernando himself opened a PR after u, merged his! haha
sorry about it, i think it was fair :)

**Comment by leifermendez** [comment]
Don't worry 🙌

**Pull request closed without merging**
