### PR TITLE
docs(contributing.md): updated the vscode extension name for containers

### PR DESCRIPTION
**Pull request by camunoz2**
This commit updates the Remote-containers extension by changing its name to Dev Containers. Additionally, it improves the workflow by replacing the old process of cloning the repository and reopening it in a dev container with a new process of directly cloning the repository link into a dev container. The previous workflow resulted in a file permission issue where all the tracked files appeared to change when running the "git status" command, even though they hadn't. This was due to overwritten file permissions.

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [X] Docs / tests

# Description

Update the name of Remote-Container extension to the new Dev Containers and changed the workflow, because the workflow proposed here result in many file changes due to permissions on my windows machine.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by zanettin** [comment]
Hi @camunoz2 👋 

Thanks a lot that you took the time to create this PR 🙏 

I just have a question regarding the changed wording since i am still getting the prompt to open my forked repo as dev container. so imo we should keep this info in the message and add the direct open via github fork as a second option. What do you think?

Bildschirmfoto 2023-02-19 um 20 46 23

**Comment by camunoz2** [comment]
> Hi @camunoz2 👋 
> 
> Thanks a lot that you took the time to create this PR 🙏 
> 
> I just have a question regarding the changed wording since i am still getting the prompt to open my forked repo as dev container. so imo we should keep this info in the message and add the direct open via github fork as a second option. What do you think?
> 
> Bildschirmfoto 2023-02-19 um 20 46 23
> 

Hi! Yeah, that would be great 👌

**Comment by zanettin** [comment]
Great! Do you want to adjust the wording in that case? So that both (the overlay and open fork from github directly) are reflected? That would be very nice 🙏  And thanks again!

**Review by zanettin — APPROVED** [review]
Thx a lot @camunoz2 🙏  great job ❤️  and welcome as new qwik contributor 🎉 👏  

cc: @manucorporat @adamdbradley: ✅

**Pull request merged**
