### PR TITLE
docs(packages/docs/src/routes/community/projects/index.mdx): add new community section and item

### PR DESCRIPTION
**Pull request by xinnks**
Add a new "Sample Applications" community section and the first item under the section, an open-source app built with Qwik and Turso.

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

This is a documentation change made to the Qwik community projects page, adding a new "Sample Applications" section and the first item under the section, an open-source newsletter manager built with Qwik and Turso.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by zanettin** [comment]
Thanks a lot @xinnks for creating this PR 🙏

**Comment by xinnks** [comment]
@zanettin Thanks for the good work you guys are doing with Qwik.

**Comment by shairez** [comment]
thanks @xinnks !

Maybe we could rename it to "Example apps?"

**Comment by xinnks** [comment]
@shairez Implemented in the latest commit cdf8ce93fc2ea155d3170edc18a70b556748bda0

**Pull request merged**
