### PR TITLE
fix(layout): fix layout for non-default html font-size 

### PR DESCRIPTION
**Pull request by asteo-net**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos
- [x] Layout Glitch

# Description

Make layout work independent of browser font-size setting.

# Use cases and why

See #5853

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] ~I have made corresponding changes to the documentation~ Not applicable
- [ ] ~Added new tests to cover the fix / functionality~ Not applicable

### CODE REVIEW

**Review by wmertens — APPROVED** [review]
LGTM

**Review by gioboa — COMMENTED** [review]
Thanks for your help @asteo-net

**Comment by wmertens** [comment]
@asteo-net unfortunately this PR breaks the sidebar. I had to revert it. Can you fix and make a new PR?

**Comment by oleasteo** [comment]
@wmertens If you can point me to the exact issue, sure. I just tested with latest changes on docs/ and community/groups/ but did not notice anything wrong. What are you looking at?

**Comment by wmertens** [comment]
clone master and go back one commit, before the revert.
The sidebar wasn't working on mobile sizes, it was only showing a darker page when you clicked it.
After reverting and deploying, the sidebar worked again

**Pull request merged**
