### PR TITLE
feat: CLI option `new`

### PR DESCRIPTION
**Pull request by zanettin**
# Overview

# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Credits to @DustinJSilk for creating this option at https://github.com/BuilderIO/qwik/pull/2426 🙏 

# Testing Instructions
- run `pnpm cli.qwik` and select `new` to follow the assistant
- run `pnpm cli.qwik new` to follow the assistant
- run `pnpm cli.qwik new help` to get the help panel
- run `pnpm cli.qwik new component` to avoid selecting the type
- run `pnpm cli.qwik new component my-component` to avoid selecting the type and the name
- run `pnpm cli.qwik new component my-component --vitest` to avoid selecting the type, name and template
- check if the CLI aborts if the file is already present
- check if the new files are generated

# Todos
- [x] validate functionality after merge
- [x] upgrade `new` option to use the new CLI design

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by DustinJSilk** [comment]
Thanks for taking this on @zanettin. You might need to have a chat with manu on the changed requirements if you havent already

**Comment by manucorporat** [comment]
is this ready to merge?

**Comment by zanettin** [comment]
@manucorporat ready for your review 👍

**Comment by manucorporat** [comment]
Got some ideas to improve this, but lets merge and iterate! so everybody can PR to it!

**Pull request merged**
