### PR TITLE
fix(routing): fallback to hard navigation when soft navigation fails.

### PR DESCRIPTION
**Pull request by iamriajul**
Issue: #5514

# Overview

This just adds a try/catch for soft navigation, so when soft navigation fails (may be due to js file does not exist) it will fallback to hard navigation using browser's `window.location.href`.

# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests / types / typos

# Description

This issue is related to: https://github.com/BuilderIO/qwik/issues/5514

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (not needed)
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by wmertens** [comment]
I like it, but I wonder:

- is setting the href the best way? What does it do for navigation history?
- can this be surprising for devs that keep a lot of state in their SPA?

For the second question, I'm thinking that it's probably ok because the user can reload the page at all times.

**Comment by iamriajul** [comment]
I'm concerned about the other cases where `onClick$` listener's code has changed! 
As per opinion: There should some kind advance control should be provided.
For example:
The developer can decide what to do when a module (might be route module, click listener module, etc) loading is failed.
The options can be like:
- do nothing - silently crash
- save the scroll state now + refresh the current page and scroll back to the place where it was so the user can click again.
- (for Route only): fallback to hard navigation.

**Comment by wmertens** [comment]
@mhevery what are your thoughts on this?

**Review by wmertens — APPROVED** [review]

**Comment by wmertens** [comment]
@iamriajul Could you rebase? The tests failed back then and I can't re-run them in this state, the rebase will trigger them.

**Comment by wmertens** [comment]
Thanks!

**Pull request merged**
