### PR TITLE
docs: Add missing server$ import in Getting started example

### PR DESCRIPTION
**Pull request by mittinatten**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests / types / typos

# Description

Adds a missing import in [part 5 of the  Getting started tutorial](https://qwik.dev/docs/getting-started/#5-tasks-and-invoking-server-code).

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by gioboa** [comment]
Hi @mittinatten thanks for your contribution. Did you try the documentation locally with `docs.dev` script?

**Comment by mittinatten** [comment]
> Hi @mittinatten thanks for your contribution. Did you try the documentation locally with `docs.dev` script?

I did now and found a typo, that is fixed. (Originally did this solely by clicking the edit button in the docs).

Building the docs changed a bunch of other files too, should those changes be included in the PR too?

**Comment by gioboa** [comment]
Are they related to your change? Can you list them pls?

**Comment by gioboa** [comment]
Yeah, It Is strange but don't worry.
Thanks ☺️ we really appreciate your help.

**Review by gioboa — APPROVED** [review]

**Pull request merged**
