### PR TITLE
chore: update Rust and all dependencies to allow wasm-pack to be installed again

### PR DESCRIPTION
**Pull request by jensmeindertsma**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Update Rust so wasm-pack can be installed again, it stopped working on older Rust versions. Also modernized all the dependency versions. This involves no breaking updates.

# Use cases and why
`cargo install wasm-pack` now completes succesfully again.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by jensmeindertsma** [comment]
Elaborating: opened this because i was following the contribution instructions which prompted me to run "cargo install wasm-pack", which then failed because the latest version of wasm pack does not compile on the current 2022 version of Rust. Ran into some dependency problems so updated dependencies where possible, making sure not to introduce breaking changes. Let me know if i made any mistakes, this was a quick attempt 🙂

**Comment by jensmeindertsma** [comment]
Having some trouble running the test suite, but cannot verify whether tests did work on my machine on `main`, because of errors with wasm-pack and wasm-bindgen, happens to be that is exactly what this PR aims to solve :)

```
> qwik-monorepo@1.2.6 test.unit /Users/jensmeindertsma/Development/qwik
> tsm node_modules/uvu/bin.js packages unit.ts --tsmconfig tsm.cjs

(node:62689) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ReferenceError: Cannot access 'dangerouslySetInnerHTML' before initialization
    at file:///Users/jensmeindertsma/Development/qwik/packages/qwik/src/core/render/dom/visitor.ts:755:4
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async Module.run (file:///Users/jensmeindertsma/Development/qwik/node_modules/.pnpm/uvu@0.5.6/node_modules/uvu/run/index.mjs:9:3)
    at async /Users/jensmeindertsma/Development/qwik/node_modules/.pnpm/uvu@0.5.6/node_modules/uvu/bin.js:26:5
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Test failed. See above for more details.
 ```
 Does anyone with experience with this repository have any pointers?

**Comment by jensmeindertsma** [comment]
Managed to work around the wasm-bindgen outdated issue on main by running `cargo install wasm-bindgen-cli --vers "0.2.84" --locked`. This could be a workaround, but this would still leave Rust severely outdated as is. This did allow me to confirm that the above error also occurs on `main` on my M1 Mac. Not sure where to look next though to resolve this test error

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
I would love to merge this, but it is currently not in a mergeable state. Can you have a look...

**Comment by gioboa** [comment]
@jensmeindertsma are you still on this PR?

**Comment by jensmeindertsma** [comment]
> @jensmeindertsma thanks for your help. are you still on this PR?

i have arch installed on a system with this cooler but haven't been able to install this PR😬 not familiar enough with AUR

**Comment by mhevery** [comment]
> i have arch installed on a system with this cooler but haven't been able to install this PR😬 not familiar enough with AUR

me neither. Anything you need from me?

**Comment by jensmeindertsma** [comment]
sorry for that weird response, was definitely more asleep than awake 😓 

I have everything running BUT the e2e tests which are persistenly failing, not sure how to debug those.

**Comment by jensmeindertsma** [comment]
Also, clippy is giving a hard error on these lines: https://github.com/BuilderIO/qwik/blob/6d0be5e2ba46dfbee76e11017abaa82124b65235/packages/qwik/src/optimizer/core/src/transform.rs#L2128-L2131

https://rust-lang.github.io/rust-clippy/master/index.html#/collection_is_never_read

I am not familiar enough with this codebase to understand what is going on in this 2000 lines+ of code file, is there anyone from the core team who could elaborate on these few lines of code?

**Comment by jensmeindertsma** [comment]
I cannot take these any further, I can get stuff to compile on my local machine, but the e2e tests just fail massively. Closing because I don't have the capacity for this at the moment.

**Pull request closed without merging**
