### PR TITLE
docs: updated example

### PR DESCRIPTION
**Pull request by the-r3aper7**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by manucorporat** [comment]
why are you changing the links? absolute is easier to maintain and refactor (moving things around does not break links)

**Comment by the-r3aper7** [comment]
I think you have tell me the [reason](https://github.com/BuilderIO/qwik/pull/1634#issuecomment-1272173122) before has it is changed since then?

**Comment by manucorporat** [comment]
The previous PR had links not pointing to any `index.mdx` file, but the path directly

**Comment by the-r3aper7** [comment]
okay i will revert those changes now

**Comment by zanettin** [comment]
Hi @the-r3aper7 
Looks like this PR is not mergable atm due to some conflicts. Would you mind to fix them?

**Comment by zanettin** [comment]
thanks a lot @the-r3aper7 🙏
@shairez @n8sabes imo ready to get merged 🎉

**Comment by shairez** [comment]
Thanks for the ping @zanettin !

And thanks for this PR @the-r3aper7 🙏

**Pull request merged**
