### PR TITLE
docs: Add getAll() cookies documentation

### PR DESCRIPTION
**Pull request by n8sabes**
This is the matching `getAll` cookies document change, if PR #2477 is accepted.

# What is it?

- [X] Feature / enhancement
- [ ] Bug
- [X] Docs / tests

# Description

This is the matching `getAll` cookies document change, if PR https://github.com/BuilderIO/qwik/pull/2477 is accepted.

# Use cases and why

# Checklist:

- [√] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [√] I have performed a self-review of my own code
- [√] I have made corresponding changes to the documentation
- [√] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by adamdbradley** [comment]
Good addition! Updated the runtime to reflect this: https://github.com/BuilderIO/qwik/pull/2482

thanks

**Comment by adamdbradley** [comment]
Will merge this once the getAll() feature is added to the runtime and published.

**Comment by zanettin** [comment]
Hi @n8sabes and @adamdbradley 
Since the provided PR (https://github.com/BuilderIO/qwik/pull/2482) was merged, are we fine to merge this changes as well?

**Comment by shairez** [comment]
thanks @n8sabes for the PR and @zanettin for the ping! 🙏
merging it

**Pull request merged**
