### PR TITLE
feat: Ability to disable default MDX plugins

### PR DESCRIPTION
**Pull request by felixsanz**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

This PR let the developer disable some MDX plugins that were included by default with qwik-city (only the optional ones and it's opt-in, by default they are enabled like before).

This plugins are remarkGfm, rehypeSyntaxHighlight and rehypeAutolinkHeadings.

It is really useful because when those plugins are disabled, the developer can now pass the same plugins to MDX with a different configuration. Right now it's impossible to re-configure rehypeAutolinkHeadings or to use another syntax hightlighter, for example.

Fixes https://github.com/BuilderIO/qwik/issues/1021.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [x] My code follows the [developer guidelines of this project](../CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by felixsanz** [comment]
@shairez This is #1177. I needed to re-create the PR because of a git mess

**Comment by shairez** [comment]
Thanks so much @felixsanz !

Summoning the all knowing @adamdbradley to take a second look to verify that everything looks good

**Comment by jrson83** [comment]
Would be awesome if merged.

**Comment by manucorporat** [comment]
lets get this merged soon!

**Comment by manucorporat** [comment]
I will look into all this next week!

**Pull request merged**
