### PR TITLE
docs: improved blog section in media

### PR DESCRIPTION
**Pull request by the-r3aper7**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

## Previously
Before

## Now
After

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by the-r3aper7** [comment]
Is there any way to optimize this?

**Comment by zanettin** [comment]
Thank you for the adjustments 🙏  imo this looks great ❤️ 
just my thoughts regarding the implementation: what do you think about adding the values right away to the the blog list instead of 'crawling' them on each request?
so adding the `imgSrc` as well here: https://github.com/BuilderIO/qwik/blob/main/packages/docs/src/routes/(ecosystem)/media/index.tsx#L156

**Comment by mhevery** [comment]
@the-r3aper7 This is a great improvement, but it can't be merged int the current state because `node-html-parser` is a node package, and the site runs at the edge (Cloudflare) where you can't have runtime dependencies on node packages (This works fine in local development because you are running in node, but will fail in Cloudflare.)

As @zanettin Could this be a build step which fetches these values so that we don't have to do it at runtime?

**Comment by the-r3aper7** [comment]
> @the-r3aper7 This is a great improvement, but it can't be merged int the current state because `node-html-parser` is a node package, and the site runs at the edge (Cloudflare) where you can't have runtime dependencies on node packages (This works fine in local development because you are running in node, but will fail in Cloudflare.)
> 
> As @zanettin Could this be a build step which fetches these values so that we don't have to do it at runtime?

yeah I was busy for days i will make it as static input

**Pull request closed without merging**
