### PR TITLE
feat: Docs search

### PR DESCRIPTION
**Pull request by youngboy**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

see docs/readme.md

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](../CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by youngboy** [comment]
preview on https://yb-qwik.pages.dev/

**Comment by manucorporat** [comment]
Amazing job! However I am a bit concerned about the eagerness of executing all react to support this. I would look into QwikReact to not run jS until the user interacts with the searchbar

**Comment by youngboy** [comment]
> Amazing job! However I am a bit concerned about the eagerness of executing all react to support this. I would look into QwikReact to not run jS until the user interacts with the searchbar

and could I help with write whole widget in qwik at all ? maybe functionality & accessible feature not comparable to official one, but I will try my best.

**Comment by youngboy** [comment]
progress update:  finished the MVP of search written in Qwik. Preview available in the same link https://yb-qwik.pages.dev/ . while it still can be improved for sophisticated UI, But I think it can be done later.


there is some issues currently I'm blocked by importing qwik component lib

when I import bundled component, showing following errors

```
Error: QWIK http://localhost:3000/src/docsearch_component_useclienteffect_zrgf0h9ksk4.js#_hW[2] does not export _hW
```

tried:
1. change `vite.config.ts` qwik plugin's option entryStrategy to `hook` works fine with app `dev.ssr`, but failed with app `build`
2. app directly import lib ts source files, works fine in `dev.ssr` & `build`, but failed with `serve`

**Comment by manucorporat** [comment]
can i see the repo of qwik-algolia search?

**Comment by manucorporat** [comment]
Found it! going to see if i can debug the issues with `_hW` make sure we are using the same version fo qwik, there are not cross compatibility yet

**Comment by manucorporat** [comment]
Thank you soo much! This was an amazing amount of work! Brilliant!

**Pull request merged**
