### PR TITLE
docs: removed useMount link and updated links

### PR DESCRIPTION
**Pull request by the-r3aper7**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by zanettin** [comment]
Hi @the-r3aper7 👋 
Just saw that this PR got merge conflicts because of some of my changes 👼 would you mind to update it again? sorry for the inconvenience and thanks for this PR 🙏

**Comment by the-r3aper7** [comment]
yeah sure

**Comment by zanettin** [comment]
thanks a lot 🙏🎉 this anchors are great! about the changes on the .md files i guess that way they are no longer rendered as checkboxes if the space is removed, right?
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#creating-task-lists
did you check that somewhere? sry for not asking that on the first loop 🙈

**Comment by the-r3aper7** [comment]
yeah you are correct they no longer rendered as checkboxes i thought it would be more easier tick without having space.

**Comment by shairez** [comment]
thanks a lot @the-r3aper7 and @zanettin !
merging

**Pull request merged**
