### PR TITLE
docs(showcase): add techtrends.nau.ch

### PR DESCRIPTION
**Pull request by finalgamer**
# Overview

Hello Qwik Team,

I'm excited to submit this pull request to add our Swiss German news website to your showcases list. We've recently launched 11 Magazines all using the same Qwik application and are thrilled with the performance enhancements and development experience provided by Qwik.

https://techtrends.nau.ch

I am not 100% sure if the tag of `news` is okay as I have not seen any other website use it. It would fit our website the most though.

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests / types / typos

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

# Acknowledgements

I'd like to thank the Qwik team for your great work. Your framework is efficient and easy for developers to use, which has helped us a lot. It's allowed us to create a fast and smooth website for our users. We're excited to show our site as an example of what Qwik can do.

### CODE REVIEW

**Comment by gioboa** [comment]
Are you using third party scripts?
https://pagespeed.web.dev/ shows some improvements

**Comment by finalgamer** [comment]
@gioboa yes we are using Google Ads, Chartbeat and Google Funding Choices.
The initial loading time in page speed insights is due to our servers only being located in Switzerland and page speed insights performing speed tests on the server closest to the user.
Would partytown help for these thirdparty scripts?

**Comment by finalgamer** [comment]
Thanks we will look into it. On the weekend my tinkering with partytown was unsuccessful sadly.

**Review by mhevery — CHANGES_REQUESTED** [review]
You need to run `cd packages/docs; pnpm run build.showcase` to update the sites.

**Comment by gioboa** [comment]
@finalgamer can you run this command pls `cd packages/docs; pnpm run build.showcase`
Than we can merge the PR I guess

**Comment by finalgamer** [comment]
Due to merge conflict I will recreate the PR. Also running the `cd packages/docs; pnpm run build.showcase` command on my own pc is not a good option as I rearely have good internet speeds and I am mostly in asia. This causes a lot worse page speed results for most pages.

I will recreate the PR when we are ready again.

**Pull request closed without merging**
