### PR TITLE
feat: bind:value for input

### PR DESCRIPTION
**Pull request by manucorporat**
```tsx
export default component$(() => {
  const value = useSignal('');
  return (
    <>
      <input bind:value={value} />
      <div>Value: {value}</div>
    </>
  );
});
```

### CODE REVIEW

**Comment by shairez** [comment]
that's awesome!

question: 
do we bind to the signal or the value of the signal?

if so, the `{value}` should probably be `{signal.value}` no?

**Comment by tleperou** [comment]
To the signal as I understood this one https://twitter.com/manucorporat/status/1637429164255879168?t=FJf423aLapRduYIbl9c2Lg&s=19.

Which events proceed with binding; input, change etc?

**Comment by shairez** [comment]
yes saw this now

IMO it's kind of confusing... as in anywhere else we're using `someSignal.value`... or else we'll be able to use "just the signal" everywhere and then it makes sense

**Comment by manucorporat** [comment]
I don’t understand what do you mean with {signal.value}?

**Comment by manucorporat** [comment]
Everywhere else you are passing the value, in this case you pass the signal, because you need two way, exactly the same as ref={}

**Comment by shairez** [comment]
Yes to pass it to `bind:value` it makes sense to pass the signal.

What I didn't realize is that you can do `{signal}` and it will work 😅
I always passed the `signal.value`

Here's an example:
https://stackblitz.com/edit/qwik-starter-qu7vul?file=src%2Froutes%2Findex.tsx

**Comment by Albuquerquess** [comment]
Boa tarde. A implementação do bind:value foi removida do repositório?

**Comment by subhendukundu** [comment]
We will need to update the lint as well?

**Comment by leighwilliams** [comment]
Working fine for text input but `bind:checked` has an issue. Seems to be using `input.value` instead of `input.checked`.

https://stackblitz.com/edit/qwik-starter-5w2pos?file=package.json,src%2Froutes%2Findex.tsx

1. Not checked - No value
Screen Shot 2023-03-31 at 10 20 11 pm
2. Checked - 'on' instead of true
Screen Shot 2023-03-31 at 10 20 23 pm
3. Unchecked - Value remains 'on'
Screen Shot 2023-03-31 at 10 20 38 pm

I'll open an issue if it's not already being addressed.

**Pull request merged**
