### PR TITLE
fix(azure): change directory layout for Azure SWA to make tooling work

### PR DESCRIPTION
**Pull request by derkoe**
Changed the directory layout for Azure Functions because the SWA CLI in the newest version could not deploy the functions from the root directory (".").

# What is it?

- [x] Feature / enhancement
- [x] Bug
- [x] Docs / tests

# Description

This is a small follow-up fix for #2384. 

With the new release of the Azure SWA client the deploy did not work anymore (see https://github.com/Azure/static-web-apps-cli/issues/615#issuecomment-1354644099). When trying to deploy the app with the API in the root folder it results in an error:

```
✖ Current directory cannot be identical to or contained within artifact folders.
```

This PR changes the directory layout so that the Azure Functions in the Static Web App are located in a folder `azure-functions`. With that the SWA CLI works again.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (no docs needed to be changed)
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by derkoe** [comment]
I have also changed this in my demo application here: https://github.com/derkoe/qwik-swa-demo/pull/6

**Comment by manucorporat** [comment]
Seems like there is a small merge conflict!

**Comment by derkoe** [comment]
@manucorporat rebased

**Comment by adamdbradley** [comment]
Awesome work @derkoe!

**Pull request merged**
