### PR TITLE
feat: View Transition API

### PR DESCRIPTION
**Pull request by swwind**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

#3664

# Use cases and why

This is very brute force implement for supporting View Transition API.

I'm not 100% sure this code doesn't introduce other problems, just for showing my solution.

https://user-images.githubusercontent.com/26316494/230405912-ef6bf8f9-a734-4ba7-bb56-6af0d87cb444.mp4

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by swwind** [comment]
@manucorporat what do you think of this :thinking:

**Comment by manucorporat** [comment]
I think this might be closer to the solution:
https://github.com/BuilderIO/qwik/pull/3684

We dont want to be blocking for too long, qwik already buffers the dom operations and commits them all in one go!

**Comment by swwind** [comment]
@manucorporat I got your idea. I made some changes accordings to your #3684, and with more stuffs.

- add an option in `<RouterOutlet />` to enable this feature manually.
- only use view transition when `routeLocation` has changed. (#3684 seems to have view transition every render, this is ideal because we may not want to have animations in signal changes)
- disable view transition if new `routeLocation` has the same `pathname` to old one. (this happens in hash link jumps)

However, `<Link href="#xxx" />` seems to be broken but I think this is a problem due to an old DOM waiting problem and could be fixed in #3244 hopefully.

**Comment by manucorporat** [comment]
Interesting approach... I think it's pretty low risk approach!

**Comment by manucorporat** [comment]
wonder if this is a RouteOutlet o QwikCityProvider api? it really configures a global thing of qwikcity

**Comment by manucorporat** [comment]
The RouterOutlet, is just an Outlet, not the render itself.

**Comment by manucorporat** [comment]
Happy to merge an iterate from here!

**Comment by swwind** [comment]
@manucorporat I moved code from RouterOutlet to QwikCityProvider, and now the API looks like this

```js
<QwikCityProvider enableViewTransitionAPI>
// ...
</QwikCityProvider>
```

In short, this code will set `document.__q_view_transition__` when the SPA `nav` function is called, and checks this mark inside Qwik to decide whether use ViewTransition API or not.

However, I still doesn't write anything when you click the Back button to go to prior page. There exists a large difference in popstate event handler between `main` and #3244, if that PR was supposed to be merged, I think it's better to wait for that interface to be stabilized.

**Comment by manucorporat** [comment]
Gonna merge and do some minor fixes, I think we can enable by default (only for transitions) + disable the html root view-name layer with css. Seems like a no risk API to instruct the browser when the naviagtion happens, then developers can opt-in using CSS

**Comment by manucorporat** [comment]
Amazing job!

**Comment by manucorporat** [comment]
The other PR, i wanna merge, but it has a big API surface + big changes

**Pull request merged**
