### PR TITLE
feat: add jsx-a eslint rule

### PR DESCRIPTION
**Pull request by kerbelp**
# Overview
Added JSLint rule for <a> tag without an href. 

# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description
An a tag with no href affects SEO score on Google's PageSpeed.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by kerbelp** [comment]
Will fix tests

**Comment by zanettin** [comment]
Hey @kerbelp 

Thanks a lot for this addition 🙏 great that you took the time to implement this 🙏 
to fix the CI issue, you just need to run `pnpm fmt`. that should be sufficient. i leave this PR open to get @manucorporat have a look at it and confirm the need of this rule.

in my personal opinion there are already similar eslint plugins out covering this (eg https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/anchor-is-valid.md) and therefor i am not 100% sure if we should add it as a qwik-specific one 👼  but i leave the decision open to the core team 😄 

thanks once again and have a great day 😃

**Comment by kerbelp** [comment]
@zanettin thanks for your comment!
Nice, if there is a rule already, then there is no need to add this PR as well.
Thanks!

**Comment by zanettin** [comment]
@kerbelp thanks for your answer. let's wait for a feedback of the core team. maybe there is a good reason to enforce it directly within the qwik rules 😃 thanks again for your submission 🙏

**Review by zanettin — APPROVED** [review]
Hi @kerbelp 👋 
Sorry for the long waiting time. The team decided to add this new rule 🎉 
Thanks again for your time and patience 🙏

**Pull request merged**
