### PR TITLE
docs: added Package manager tabs

### PR DESCRIPTION
**Pull request by the-r3aper7**
# Overview

# What is it?

image
image

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by gioboa** [comment]
This is so cool. Thanks 🚀

**Comment by gioboa** [comment]
Qwik UI has tabs component, I think we can use that instead of a completely fresh implementation. What do you think @shairez ?

**Comment by shairez** [comment]
great work @the-r3aper7 !

Yeah I agree @gioboa 
We already fixed a lot of bugs in [Qwik UI tabs](https://qwikui.com/docs/headless/tabs/) (SSR, index management, etc)

You can use the headless component and just match to the styles you've written

There's even a shorthand syntax version to write a simple tabs component - 

```tsx
<Tabs>
      <TabPanel title="Tab 1">Content 1</TabPanel>
      <TabPanel title="Tab 2">Content 2</TabPanel>
      <TabPanel title="Tab 3">Content 3</TabPanel>
</Tabs>
```

**Comment by the-r3aper7** [comment]
how can i resolve this conflicts?

**Review by mhevery — CHANGES_REQUESTED** [review]
Thank you for your contribution. The changes look great, but this PR will have to wait until https://github.com/BuilderIO/qwik/issues/5097 is resolved.

**Comment by mhevery** [comment]
> Qwik UI has tabs component, I think we can use that instead of a completely fresh implementation. What do you think @shairez ?

But that means that https://github.com/BuilderIO/qwik/issues/5097 will block the merging.... 🤔

**Comment by shairez** [comment]
Yep, if it was a specific problem of Qwik UI I would have suggested to merge something simpler, but we need to fix this in Qwik anyway, so I think it's better wait a bit and use Qwik UI for an accessible tabs component.

**Comment by gioboa** [comment]
@the-r3aper7 the issue with Qwik UI  is solved.
We can finalise the PR with the latest version of the library.
Would you like to complete it or do you need an help?

**Comment by the-r3aper7** [comment]
i will complete the remaining work and make a PR by tomorrow currently i am traveling.

**Comment by the-r3aper7** [comment]
> @the-r3aper7 the issue with Qwik UI  is solved.
> We can finalise the PR with the latest version of the library.
> Would you like to complete it or do you need an help?

i will complete the remaining work and make a PR by tomorrow currently i am traveling.

**Comment by the-r3aper7** [comment]
i have created a new [PR](https://github.com/BuilderIO/qwik/pull/5649) regarding this to avoid any conflicts. I am closing this now

**Pull request closed without merging**
