### PR TITLE
Create navlink-component.tsx

### PR DESCRIPTION
**Pull request by Adbib**
NavLink is a component that allows you to create a simple Link with isPending and isActive status and props. you can use it mainly in dashboards navbars ,headers nav, and footer...

# Overview

# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Add NavLink component

This PR adds a new NavLink component that extends the Link component from qwik-city. 

The NavLink component adds the following props:

- isActive - Applies a class when the current location url matches the link href. Useful for styling the active navigation link.

- isPending - Applies a class when the router is navigating to the link. Useful for showing a pending state on the link. 

The component checks the current location pathname against the link href to determine isActive status, and uses the isNavigating hook from useLocation to check isPending status.

This allows creating navigation links that can show active and pending styling, making it easy to build navigation components for dashboards, navbars, headers, footers, etc.

Usage:

```jsx
<NavLink href="/" isActive="active" isPending="pending">
  Home
</NavLink>
```

# Use cases and why

- 1. header nav
- 2. Dashboard navbars

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by gioboa** [comment]
Thanks @Adbib for your contribution
I think this awesome component could be inserted inside the [cookbook](https://qwik.builder.io/docs/cookbook/). The core team is extremely cautious to about expanding the API surface area of Qwik. Because it means more stuff to document, maintain and ensure that all of the surface area has the same "feel".

**Comment by Adbib** [comment]
> Thanks @Adbib for your contribution I think this awesome component could be inserted inside the [cookbook](https://qwik.builder.io/docs/cookbook/). The core team is extremely cautious to about expanding the API surface area of Qwik. Because it means more stuff to document, maintain and ensure that all of the surface area has the same "feel".

Thank you @gioboa  
Yeah, I understand what the core team direction is, I think people we gonna need to use this component every time they build an app.
I will take care of the docs when the component published

**Comment by gioboa** [comment]
The idea is to showcase your solution in the cookbook, like the portal one. https://qwik.builder.io/docs/cookbook/portal/#solution
So you can show how wrap the official Link component. Let's me know if it's not clear. Thanks

**Comment by Adbib** [comment]
> The idea is to showcase your solution in the cookbook, like the portal one. https://qwik.builder.io/docs/cookbook/portal/#solution So you can show how wrap the official Link component. Let's me know if it's not clear. Thanks

Thanks, I added it , you can check it from here: https://github.com/BuilderIO/qwik/pull/5621

**Comment by gioboa** [comment]
I close this one.

**Pull request closed without merging**
