### PR TITLE
Added new site to showcase room

### PR DESCRIPTION
**Pull request by adnanebrahimi**
tatbiqit.com is the official website of Tatbiqit company located in Kuwait developed by Qwik.

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

Adding a new website to the showcase page, this website is the official website of a Kuwaiti company called Tatbiqit.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by Dindaleon** [comment]
Hello,

The first load is almost 300kB of javascript, isn't Qwik suppose to be 0b load of js? Is it possible to make your site load 0b js? Just wondering, otherwise, I believe it would the defeat one of the main purposes of using qwik.

**Comment by adnanebrahimi** [comment]
@Dindaleon 
I believe you have seen some js in the network tab which is from cloudflare email protection. 
Other js that is loading externally is Google analytics service which is loaded by partytown

**Comment by Dindaleon** [comment]
Please let me know if I am looking at the wrong thing. I capture my network tab when loading the site. I do see cloudflare and email protection but I also see a bunch of `q-` prefixed js.

Screenshot 2023-02-08 at 2 36 04 PM

**Comment by adnanebrahimi** [comment]
Did you clear the network tab before reloading? Because I see the request get duplicated. I will check it once i get back at my desk

**Comment by Dindaleon** [comment]
> tatbiqit.com

yeah, I cleared it. Please let me know what's going on because I am very curious about it. While writing some code I noticed that whatever we put inside `useClientEffect$` hook will run on load once no matter what. However, if we want to lazy load the code, we need to use other hooks such as `useTask`

**Comment by adnanebrahimi** [comment]
@Dindaleon 
I didn't see anything abnormal in the request waterfall.
https://gtmetrix.com/reports/tatbiqit.com/O85dXETV/

**Comment by Dindaleon** [comment]
Those files are not being downloaded by the service worker. They are being downloaded directly.

**Pull request merged**
