### PR TITLE
docs: upgrade qwik version and replace useClicentEffect$

### PR DESCRIPTION
**Pull request by cunzaizhuyi**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [X] Docs / tests

# Description

docs: upgrade qwik qwik-city version and replace useClicentEffect$ api in example.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by zanettin** [comment]
Hi @cunzaizhuyi 👋 
Guess this PR is a duplicate of https://github.com/BuilderIO/qwik/pull/3077, right? Except for the package maintenance which conflicts atm? Would you mind if we close this one? Thanks again for your contribution 🙏

**Comment by cunzaizhuyi** [comment]
It is not same with #3077。They are two places。

**Comment by zanettin** [comment]
Oh right 👀  sorry for that 🙈 would you mind to revert the package upgrades on this PR? would like to leave the upgrades to @manucorporat and team 👼 thanks again for your contributions 🙏

**Comment by cunzaizhuyi** [comment]
> Oh right 👀 sorry for that 🙈 would you mind to revert the package upgrades on this PR? would like to leave the upgrades to @manucorporat and team 👼 thanks again for your contributions 🙏

a new pr in #3103

**Pull request closed without merging**
