### PR TITLE
Fix: losing this context when multiple server functions are calls in one useResource$ hook

### LINKED ISSUE #4417: [🐞] `this` is undefined in server$ function when called consequentially.
### Which component is affected?

Qwik City (routing)

### Describe the bug

When two or more `$server` functions called one after each other the second called function would have `this === undefined`

This doesn't happen when they called concurrently in `Promise.all`

```ts
const serverFunctionA = server$(async function () {
  console.log('serverFunctionA', this);
  return true;
});

const serverFunctionB = server$(async function () {
  console.log('serverFunctionB', this); // <--- here `this` would be undefined
  return true;
});

export default component$(() => {
  const resource = useResource$(async () => {
    const resultA = await serverFunctionA();
    const resultB = await serverFunctionB();

    return { resultA, resultB };
  });

  return (
    <Resource
      value={resource}
      onResolved={({ resultA, resultB }) => (
        <>
          {resultA} {resultB}
        </>
      )}
    />
  );
});
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-jdcnqd?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

_No response_

### System Info

```shell
System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 75.86 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 3.5.1 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 95.0.2
    Safari: 16.4
  npmPackages:
    @builder.io/qwik: 1.1.4 => 1.1.4 
    @builder.io/qwik-city: ~1.1.4 => 1.1.4 
    @builder.io/qwik-react: ^0.5.0 => 0.5.0 
    undici: 5.21.0 => 5.21.0 
    vite: 4.2.1 => 4.2.1
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hassanzohdy**
# Overview

So, this PR fixes losing `this` context in server functions if they are called inside `useResource$` hook (#4417) and also introduce a new helper function to the passed object to the resource callback function called `call`.

The idea is to keep tracking of current context of the resource when initially called and use it in any inner function calls that uses promises to perform some actions (i.e calling multiple server functions sequentially).

### Usage
```tsx
import { server$ } from "@builder.io/qwik-city";
import {
  $,
  Resource,
  component$,
  useResource$,
} from "@builder.io/qwik";

const sleep = async (ms: number) =>
  new Promise((resolve) => setTimeout(resolve, ms));

const serverFunctionA = server$(async function SererA() {
  await sleep(4000);

  return "A";
});

const serverFunctionB = server$(async function ServerB(name: string) {
  await sleep(3000);

  return name;
});

const serverFunctionC = server$(async function ServerC() {
  await sleep(2000);

  return "C";
});

export const ResCaller= component$(() => {
  const resource = useResource$(
    $(async ({ call }) => {
    /**
     * The call function is used to keep track of the current context it accepts any function that
     * will be executed and rest of params are passed as arguments to the function using `call`
     * function is only needed when there functions (i.e server functions) that run sequentially and
     * need to be executed in the same context
     */
      const a = await call(serverFunctionA);
      const b = await call(serverFunctionB, "Hello");
      const c = await call(serverFunctionC);

      return { a, b, c };
    }),
  );

  return (
    <Resource
      value={resource}
      onResolved={(d) => {
        console.log("Resolved!", d);

        return <div>Done</div>;
      }}
    />
  );
});
```

I've tested it in multiple concurrent requests and it works fine.

# What is it?

- [ x ] Feature / enhancement
- [ x ] Bug
- [ ] Docs / tests / types / typos

# Description

This PR fixes #4417 when server functions are called in sequence in useResource$ hook.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by gioboa** [comment]
Thanks @hassanzohdy 
Did you try with concurrent request?
This kind of implementation with a global variable is not "request safe". multiple requests at the same time can recreate the problem because the global variable mess us things.

**Comment by hassanzohdy** [comment]
@gioboa You're right, the previous solution failed with concurrent requests, i fixed it by introducing a new helper function to the resource object called `call` which will be mainly needed when sequential functions are needed to be called, it keeps the resource `context`.

If everything is okay, i'll update the docs to highlight the `call` function in the `useResource$` docs.

**Comment by wmertens** [comment]
@hassanzohdy unfortunately invoke isn't magic either, as soon as the called function goes async things are broken again.

The solution is using async localstorage and I started a PR but didn't finish it.

**Comment by hassanzohdy** [comment]
@wmertens the idea here is simple, each time an async function will be called in sequence, it should be wrapped with `call` helper function, it will use the same context by calling the async function and will not lose the context.

**Comment by wmertens** [comment]
whenever a server function awaits, another server function can be called and it will change the global context that invokeFn maintains. You're just moving the problem.

If invokeFn worked, it would already work.

See https://github.com/BuilderIO/qwik/pull/5510

**Review by wmertens — CHANGES_REQUESTED** [review]
As discussed, cannot be merged with the current implementation

**Pull request closed without merging**
