### PR TITLE
Add new videos to the media page

### PR DESCRIPTION
**Pull request by Vasudevatirupathinaidu**
# What is it?
   Added videos and docs
- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

I have added new videos to the media page and changed the position of a few videos.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by shairez** [comment]
Thanks @Vasudevatirupathinaidu ! 

Can you please fix the linting issue?

**Comment by Vasudevatirupathinaidu** [comment]
Hey brother @shairez! I have a hard time resolving this issue. Maybe you can create a pull request for this. Let me know how can I send the list of videos and docs to you.

**Comment by shairez** [comment]
No worries @Vasudevatirupathinaidu 
I'll help you out

What you want to do is to run 
`pnpx prettier --write packages/docs/src/routes/media/index.tsx`

And then commit and push the result

we should probably add an automated way to solve these issues (I might add a way today)

In the meantime, this is how you fix the prettier issue

thanks!

**Comment by Vasudevatirupathinaidu** [comment]
Thanks, @shairez, I think this will work. But something is wrong on my end. So, I will close this PR and will create a new one. Sorry for the trouble.

**Comment by shairez** [comment]
no worries

thanks

**Pull request closed without merging**
