### PR TITLE
fix(tsconfig.json): add DOM.Iterable to compilerOptions of tsconfig.json

### PR DESCRIPTION
**Pull request by OmkarKirpan**
# What is it?

- [ ] Feature / enhancement
- [X] Bug
- [ ] Docs / tests

# Description

resolves issue: #1344

# Use cases and why

### Expected Behaviour
Code example:
```
export const onPost: RequestHandler = async ({ request }) => {
  const payload = Object.fromEntries(await request.formData());
}
```
### Actual Behaviour
TypeScript warning:
```
  Overload 1 of 2, '(entries: Iterable<readonly [PropertyKey, any]>): { [k: string]: any; }', gave the following error.
    Argument of type 'FormData' is not assignable to parameter of type 'Iterable<readonly [PropertyKey, any]>'.
      Property '[Symbol.iterator]' is missing in type 'FormData' but required in type 'Iterable<readonly [PropertyKey, any]>'.
  Overload 2 of 2, '(entries: Iterable<readonly any[]>): any', gave the following error.
    Argument of type 'FormData' is not assignable to parameter of type 'Iterable<readonly any[]>'.
      Property '[Symbol.iterator]' is missing in type 'FormData' but required in type 'Iterable<readonly any[]>'.
```

# Checklist:

- [x] My code follows the [developer guidelines of this project](../CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by manucorporat** [comment]
Seems like lint ci is failing probably because your IDE changed the identation of the file?

**Comment by OmkarKirpan** [comment]
> Seems like lint ci is failing probably because your IDE changed the identation of the file?

@manucorporat, line ending got changed from LF to CRLF.
You can add prettier fix to lint-staged, so when commiting it will run prettier hook or else add gitattributes file.

I have updated the file with LF, also ran prettier fix, could you please rerun the workflows?

**Comment by shairez** [comment]
Great suggestion @OmkarKirpan ! thanks

Want to add a PR for that?

**Comment by OmkarKirpan** [comment]
> Great suggestion @OmkarKirpan ! thanks
> 
> Want to add a separate PR for that?

Sure, I'll do that.

**Pull request merged**
