### PR TITLE
docs: add css-scanner to showcase

### PR DESCRIPTION
**Pull request by Makhene**
Added https://css-scanner.com to list.

# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by zanettin** [comment]
Hi @Makhene 👋 
Thanks for submitting this page 🙏 
Just checked the page speed insight scores of the site and it is atm at [77}(https://pagespeed.web.dev/analysis/https-css-scanner-com/s9pdmfwvi8?form_factor=mobile) for mobile.
Do you think you find some time to have a look at the mentioned performance improvements? to reduce the impact of gtm i would recommend to use partytown (can be installed using the qwik cli 🎉 )
Thanks again 🙏

**Comment by mhevery** [comment]
@zanettin The performance seems to be fixed now. Should we merge?

**Comment by zanettin** [comment]
@mhevery thx for the retest 🙏 just checked it, and it is currently at [55 on mobile](https://pagespeed.web.dev/analysis/https-css-scanner-com/lcv4xxusg1?form_factor=mobile) atm. leave the decission up to u 👼

**Comment by zanettin** [comment]
I've just re-checked it, and the page is still on 55. I'm closing this PR for now, but I would love to see it re-opened when the performance issues are fixed. 🙏

**Pull request closed without merging**
