### PR TITLE
refactor(insights): improve consistency 

### PR DESCRIPTION
**Pull request by iamriajul**
# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Nothing related to features or bugs. It is just a coding enhancement. making sure Single Source of Truth.

### CODE REVIEW

**Review by gioboa — APPROVED** [review]
Thanks @iamriajul 💪

**Comment by gioboa** [comment]
I'm thinking about this change, did you find any problem in the previous code?

**Comment by iamriajul** [comment]
> I'm thinking about this change, did you find any problem in the previous code?

No problem in the previous code, it is just best practice to follow the Single Source of Truth.

**Comment by iamriajul** [comment]
This will work smoothly, As I've already deployed insights in our environment for staging & production sites without any problem. And working perfectly.

**Pull request merged**
