### PR TITLE
docs(qwik-city): refactor 404 dynamic example to avoid JSX branching 

### PR DESCRIPTION
**Pull request by felixsanz**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

Qwik optimizes code when JSX doesn't return multiple times, let's return just once with a ternary

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by zanettin** [comment]
Hi @felixsanz 👋 
Thanks for this PR 🙏 tbh i am not aware of the mentioned optimization step when just a single return is in the function body. so i have to hand this over to @adamdbradley and @manucorporat 🙏 
Thanks once again for your time and contribution 🎉

**Comment by felixsanz** [comment]
> Hi @felixsanz wave Thanks for this PR pray tbh i am not aware of the mentioned optimization step when just a single return is in the function body. so i have to hand this over to @adamdbradley and @manucorporat pray Thanks once again for your time and contribution tada

Ey! Manu explained here: https://discord.com/channels/842438759945601056/1042118392708087989/1042403559842517012

**Comment by zanettin** [comment]
Thanks for sharing the discussion 🙏

**Comment by manucorporat** [comment]
I would love to get rid of this eslint rule all together, but need to figure out how the optimizer understand some JSX, hard to in a single pass

**Comment by manucorporat** [comment]
I think the new code still has two branches, we would need a `<>` fragment at the root level

**Comment by felixsanz** [comment]
> I think the new code still has two branches, we would need a `<>` fragment at the root level

it doesn't. I use this technique and 

> I think the new code still has two branches, we would need a `<>` fragment at the root level

But that's a bug with the lint rule? It's already reported here: https://github.com/BuilderIO/qwik/issues/2685

And there is a complain about the 404 docs page, which is what this PR is about.

Not sure if this PR is wanted or the eslint rule is about to dissapear and not worth it. You say!

**Comment by zanettin** [comment]
Hi @felixsanz 👋 
Manu fixed this issue yesterday with this PR https://github.com/BuilderIO/qwik/pull/3034. So multi root is now a thing without performance drops 🎉 . Hope these are great news for you as well. Thanks once again for this PR and your time 🙏

**Comment by felixsanz** [comment]
So not needed! :) np!

**Comment by zanettin** [comment]
Thanks once again! 🙏

**Pull request closed without merging**
