### PR TITLE
fix: A bug fix #5104

### LINKED ISSUE #5104: [🐞] CLI - Build script silences failed steps when running with Yarn
### Which component is affected?

Starters / CLI

### Describe the bug

If you use Yarn, running the `yarn build` command while there are (for example) linting issues will prematurely exit the process without printing anything about why it failed.

### Reproduction

https://stackblitz.com/edit/qwik-starter-pcpq7a?file=src%2Froot.tsx

### Steps to reproduce

* Make a compiling but invalid change in a file (e.g. declare an unused variable in `src/root.tsx`)
* Run `yarn build`
* The command will fail without printing any valuable information on what failed

Here's an example:
```
$ yarn build
      ............
    .::: :--------:.
   .::::  .:-------:.
  .:::::.   .:-------.
  ::::::.     .:------.
 ::::::.        :-----:
 ::::::.       .:-----.
  :::::::.     .-----.
   ::::::::..   ---:.
    .:::::::::. :-:.
     ..::::::::::::
             ...::::
     


yarn run build.types
yarn run build.client
yarn run lint

$ vite build
vite v4.4.7 building for production...
✓ 95 modules transformed.
dist/build/q-8f7ef15c.webp   3.96 kB
dist/build/q-da3d1958.webp   7.49 kB
dist/build/q-85611e8a.webp  11.42 kB
dist/build/q-e86984e2.webp  15.85 kB
dist/build/q-7df0c9e1.webp  27.56 kB
dist/q-manifest.json        30.97 kB │ gzip:  5.41 kB
dist/build/q-027f67b0.css    4.00 kB │ gzip:  1.28 kB
dist/build/q-86630e49.js     0.13 kB │ gzip:  0.12 kB
dist/build/q-ff9c7aea.js     0.13 kB │ gzip:  0.13 kB
dist/build/q-dcd6eea6.js     0.21 kB │ gzip:  0.16 kB
dist/build/q-41dd0fb6.js     0.24 kB │ gzip:  0.19 kB
dist/build/q-c37f9393.js     0.26 kB │ gzip:  0.21 kB
dist/build/q-d0ad1337.js     0.31 kB │ gzip:  0.23 kB
dist/build/q-0b186ed1.js     0.38 kB │ gzip:  0.28 kB
dist/build/q-ffc9fb89.js     0.41 kB │ gzip:  0.29 kB
dist/build/q-51da6c56.js     0.47 kB │ gzip:  0.32 kB
dist/build/q-b2942bd8.js     0.54 kB │ gzip:  0.32 kB
dist/build/q-599a7cd5.js     0.55 kB │ gzip:  0.35 kB
dist/build/q-22949cf9.js     0.70 kB │ gzip:  0.44 kB
dist/build/q-4fd745e3.js     0.75 kB │ gzip:  0.45 kB
dist/build/q-3be6cc27.js     0.77 kB │ gzip:  0.41 kB
dist/build/q-c2a8b70a.js     0.79 kB │ gzip:  0.51 kB
dist/build/q-6022aabb.js     0.89 kB │ gzip:  0.55 kB
dist/build/q-cb96be76.js     0.96 kB │ gzip:  0.51 kB
dist/build/q-a8001a11.js     1.04 kB │ gzip:  0.65 kB
dist/build/q-25e27e0c.js     1.14 kB │ gzip:  0.67 kB
dist/build/q-3eab91df.js     1.15 kB │ gzip:  0.64 kB
dist/build/q-856e3d49.js     1.17 kB │ gzip:  0.58 kB
dist/build/q-8b587fdb.js     1.20 kB │ gzip:  0.62 kB
dist/build/q-44d16505.js     1.50 kB │ gzip:  0.73 kB
dist/build/q-3262ec8a.js     1.67 kB │ gzip:  0.89 kB
dist/build/q-663033b0.js     2.29 kB │ gzip:  1.11 kB
dist/service-worker.js       2.54 kB │ gzip:  1.21 kB
dist/build/q-de896cde.js     2.69 kB │ gzip:  1.23 kB
dist/build/q-0db0dd48.js     2.83 kB │ gzip:  0.95 kB
dist/build/q-cb2d40cb.js     3.82 kB │ gzip:  1.83 kB
dist/build/q-13e363e3.js     5.40 kB │ gzip:  2.14 kB
dist/build/q-f2a74367.js     5.85 kB │ gzip:  2.45 kB
dist/build/q-070b48f1.js     8.75 kB │ gzip:  4.13 kB
dist/build/q-1e8e1aad.js    49.24 kB │ gzip: 20.00 kB
✓ built in 3.63s

✓ Built client modules

error Command failed with exit code 1.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: ^1.2.10 => 1.2.10 
    @builder.io/qwik-city: ^1.2.10 => 1.2.10 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7
```

### Additional Information

I tried with more recent versions of Node (v20.5.1) and Yarn (v4.0.0-rc.50), but it's the same.

### PR DESCRIPTION
**Pull request by Charlygraphy23**
…arn #5104

# Overview

# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests / types / typos

# Description

> If you use Yarn, running the yarn build command while there are (for example) linting issues will prematurely exit the process without printing anything about why it failed.

# Use cases and why

- 1. If we run `yarn build` and if there is any linting issue then `yarn build` simply get exit with 1 without showing exact issue of linting. To solve that while checking the linting on the build file, I found that the error is not showing properly with `e.stderr` but in the `e.stdout`, we are getting fulll error with description.

So i switched the if condition - 

```diff

- if (e.stderr) {
-        console.log(e.stderr);
     } else {
-        console.log(e.e.stderr);
      }

+ if (e.stdout) {
+       console.log(e.stdout);
       } else {
+        console.log(e.stderr);
     }

```

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by wmertens** [comment]
Shouldn't both outputs be logged, and stderr to log.error?

**Comment by Charlygraphy23** [comment]
> Shouldn't both outputs be logged, and stderr to log.error?

It seems that if we only log `e.stdout` for both cases its works `npm`, `yarn`, and `pnpm`.  You are right `e.stderr` logged out with `console.error`.

**Comment by wmertens** [comment]
So will you make that change?

**Comment by Charlygraphy23** [comment]
> So will you make that change?

Yes i will make the change

**Review by wmertens — APPROVED** [review]

**Pull request merged**
