### PR TITLE
Export platform specific request handlers

### PR DESCRIPTION
**Pull request by nnelgxorz**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

Screenshot from 2022-10-22 18-33-13

For a while now, we've had the platform field on available on the RequestHandler type, but the field is typed to unknown and most users are completely unaware that it exists.

This PR exports special RequestHandler* types from the middlewares for users to take advantage of when developing for their specific platform.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by nnelgxorz** [comment]
Not sure what's happening with the build error. Is `@public` not the correct tag for these type exports?

**Comment by manucorporat** [comment]
It's ` * @alpha`

**Comment by manucorporat** [comment]
I think it's a great PR!

**Comment by nnelgxorz** [comment]
Thanks. Jeez. Still not building after using alpha tags and running yarn api.update. Not sure what I broke.

**Comment by nnelgxorz** [comment]
I guess it works better when you run api.update from the project root. Should be good now!

**Pull request merged**
