### PR TITLE
fix(layout): fix layout for non-default html font-size / revision 2

### PR DESCRIPTION
**Pull request by oleasteo**
Second revision of PR #6007 due to issues with first PR. @wmertens 

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos
- [x] Layout Glitch

# Description

Make layout work independent of browser font-size setting.

# Use cases and why

See #5853

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] ~I have made corresponding changes to the documentation~
- [ ] ~Added new tests to cover the fix / functionality~

### CODE REVIEW

**Comment by shairez** [comment]
@wmertens @oleasteo this PR removed the ` <OnThisPage />` sidebar

Was that done by mistake? or was it on purpose?

**Comment by oleasteo** [comment]
I considered it dead code. Was I wrong?

```jsx
  const noRightMenu = ['/docs/'].includes(loc.url.pathname);
  // [...]
        class={{
          'no-right-menu': noRightMenu,
        }}
```
within /routes/docs/layout.tsx file would always be true. Wouldn't it?

In combination with
```css
.docs main.no-right-menu .on-this-page {
  display: none;
}
```
this did essentially hide it in all cases.

**Comment by shairez** [comment]
Well, if you revert these PR changes the side-menu appears

**Comment by oleasteo** [comment]
Ah, my bad: I did not read `['/docs/'].includes(loc.url.pathname)` properly; it only matches the exact /docs/ url, not sub-pages. Sorry for this.

So yes, it's been a mistake. Should I create a fix or are you on it anyway?

**Comment by shairez** [comment]
Yeah if you can it would be great!
Thanks!

**Pull request merged**
