### PR TITLE
feat(qwik-city): Adding Script Tag to Head Tag via DocumentHead

### PR DESCRIPTION
**Pull request by Harkunwar**
Feat #2593

# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

This adds a script tag to the head tag similar to how style tag is added at the moment. I also took a moment to update the props field for style tag to take in the style attributes only instead of an arbitrary key-value pair.

# Use cases and why

This is important for dev experience. More discussion present in #2593

- 1. One use case
- 2. Another use case

# Checklist:

- [X] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by zanettin** [comment]
Hi @Harkunwar 👋 
Thanks a lot for this PR 🎉 
To make the CI happy as well, we need an update on the API docs which can be tiggered via `pnpm api.update` 🙏

**Review by mhevery — APPROVED** [review]

**Comment by GrandSchtroumpf** [comment]
Hello, any news on this PR ?
It would be a good workaround for this issue too: https://github.com/BuilderIO/qwik/issues/2926

**Review by wmertens — COMMENTED** [review]
LGTM!

**Review by zanettin — APPROVED** [review]
thx @Harkunwar for this feature and @wmertens for your review 🙏

**Pull request merged**
