### PR TITLE
feat: add qwik/no-use-visible-task eslint rule

### PR DESCRIPTION
**Pull request by gioboa**
We did a pair programming PR

Co-authored-by: Matteo Pietro Dazzi <ilteoood@users.noreply.github.com>
Co-authored-by: Pasquale De Lucia <pasquale.delucia96@gmail.com>
Co-authored-by: Gloria Giannascoli <gloriag-dev@users.noreply.github.com>
Co-authored-by: pietrodev07 <pietrodev07@users.noreply.github.com>

# Overview

# What is it?

- [X] Feature / enhancement

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by wmertens** [comment]
@gioboa It should also list alternatives:

- run on SSR with useTask
- run in event handlers like onClick
- run during render but inside `if (isBrowser)`

**Comment by gioboa** [comment]
These are not always viable alternatives because if you need window or document you need useVisibleTask$

**Comment by thejackshelton** [comment]
Added context:
https://discord.com/channels/842438759945601056/1175555132012908544

**Comment by zanettin** [comment]
can we also extend the eslint docs page? 👼 
https://qwik.builder.io/docs/advanced/eslint/

**Comment by gioboa** [comment]
Sure, I didn't know about this page

**Comment by wmertens** [comment]
LGTM but it's not yet clear if we should add this.

**Comment by gioboa** [comment]
> LGTM but it's not yet clear if we should add this.

Core team member asked for it, the community is complaining about that 🤷🏼‍♂️ 
I haven't a strong opinion on that

**Comment by gioboa** [comment]
I added the eslint rule in the docs

Screenshot 2023-11-19 at 14 38 40

Screenshot 2023-11-19 at 14 38 16

**Comment by PatrickJS** [comment]
@gioboa @wmertens 
just merge it. can always revert if anyone complains

**Review by PatrickJS — APPROVED** [review]

**Pull request merged**
