### PR TITLE
docs: problem and solution on resource tutorial are no longer equal

### PR DESCRIPTION
**Pull request by mimafogeus2**
# What is it?

- [ ] Feature / enhancement
- [X] Bug
- [X] Docs / tests

# Description

In the tutorial Resource section, the initial problem's code is similar to the solution. This PR replaces the solution parts with placeholders.

### CODE REVIEW

**Comment by zanettin** [comment]
Hi @mimafogeus2 👋 
Thanks for creating this PR 🙏 
I just had a look at the initial state and the solution and they are different atm. We wanted to have the tutorials focusing on the topic and not make it a to hard to solve challenge 😆 

What do you think? Should we still remove more from the question or is the diff big enough to get new devs into the topic?
Bildschirmfoto 2023-02-18 um 13 16 20

**Comment by mimafogeus2** [comment]
Hey

I just looked at the `BuilderIO:main` branch and it seems like the problem and solution are similar.
What am I missing? Am I looking at the wrong branch?

**Comment by zanettin** [comment]
OMG 😆  sry that was my bad 🙈  we have two identical pages in the docs 🙈 

https://qwik.builder.io/tutorial/introduction/resource/
https://qwik.builder.io/tutorial/reactivity/resource/

same wording but not the same problem and solutions assigned...
would you mind to re-use the values from this problem? https://github.com/BuilderIO/qwik/blob/main/packages/docs/src/routes/tutorial/reactivity/resource/problem/app.tsx

Thanks a lot and sorry again for the confusion!

**Comment by zanettin** [comment]
Hi @mimafogeus2 👋 
Wanted to ask quickly if you would have time for the mentioned adjustment 👼  if not, pls leave me a quick note 🙏  thanks again for creating this PR 🙏

**Pull request merged**
