### PR TITLE
docs: drop mutable()

### PR DESCRIPTION
**Pull request by GustavoMelloGit**
removes mutable() function at passing stores docs as it was deprecated

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

This change removes the usage of mutable() function as now it is deprecated and everything is now mutable

# Checklist:

- [x] My code follows the [developer guidelines of this project](../CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by shairez** [comment]
Thanks @GustavoMelloGit !

Seems like it's failing on prettier errors

Can you please run it locally and fix those errors?

Thanks!

**Comment by GustavoMelloGit** [comment]
> Thanks @GustavoMelloGit !
> 
> Seems like it's failing on prettier errors
> 
> Can you please run it locally and fix those errors?
> 
> Thanks!

Thats strange, i ran both prettier.fix and lint.prettier scripts and no errors found.

`root@dc9574fd35c0:/workspaces/qwik# yarn lint.prettier
Checking formatting...
All matched files use Prettier code style!`

Can you help me with that?

**Comment by shairez** [comment]
thanks @GustavoMelloGit !

You can point prettier --fix to the specific files with the warnings  -

packages/docs/src/routes/tutorial/props/store/problem/app.tsx

and 

packages/docs/src/routes/tutorial/props/store/solution/app.tsx

image


(from here - 
https://github.com/BuilderIO/qwik/actions/runs/3210863322/jobs/5249434467 )

**Comment by GustavoMelloGit** [comment]
Same thing, no errors found.

**Comment by shairez** [comment]
weird, let me try to run it locally

**Comment by GustavoMelloGit** [comment]
I dont know if i am doing something wrong, but it does not change anything, but it is saying that it has an error

```
root@dc9574fd35c0:/workspaces/qwik# yarn prettier -w packages/docs/src/routes/tutorial/props/store/problem/app.tsx
packages/docs/src/routes/tutorial/props/store/problem/app.tsx 444ms
root@dc9574fd35c0:/workspaces/qwik# yarn prettier -w packages/docs/src/routes/tutorial/props/store/solution/app.tsx
packages/docs/src/routes/tutorial/props/store/solution/app.tsx 441ms
```

**Comment by ulic75** [comment]
Since it's the WHOLE file that appears in the diff, I might guess line endings.  Off the top of my head I'm not sure if github diffs show line endings.

**Comment by GustavoMelloGit** [comment]
@ulic75 i am running it on dev container and it is by default LF, i dont know if it is a problem

**Comment by shairez** [comment]
Good catch @ulic75 

Sounds like it might be it

I just ran it on a windows machine and it shows me a warning, but when I run `pretter --fix` I see that it's change but nothing was changed in the diff (though the file can be committed), so it must be the invisible line endings or something

**Comment by GustavoMelloGit** [comment]
@shairez Can you commit it for me? i cannot commit these files since it does not shows any changes for me

**Comment by nnelgxorz** [comment]
Are you using VSCode? You should be able to change line breaks on a per file basis. https://dev.to/wagslane/how-to-get-consistent-line-breaks-in-vs-code-lf-vs-crlf-2c3p

**Comment by shairez** [comment]
@GustavoMelloGit just did it... let's see if it works :)

**Comment by GustavoMelloGit** [comment]
Thank you @shairez, it is ready for merge now

**Comment by shairez** [comment]
Yep looks like we made it! 🎉 😄 
Thanks for the contribution @GustavoMelloGit !

**Pull request merged**
