### PR TITLE
feat: add comment into the starter template for required `title` element editor hint

### PR DESCRIPTION
**Pull request by cunzaizhuyi**
# What is it?

- [X] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

add required `title` element into the starter template, for better SEO. 

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by manucorporat** [comment]
The title is already in the starters:
https://github.com/BuilderIO/qwik/blob/b45bb4668d219b8db84828b746c82e49fa84eddd/starters/apps/basic/src/components/router-head/router-head.tsx#L13

Also, `<meta charSet="utf-8" />` has to be always the first tag! 

Wonder if this PR can be a comment instead.

**Comment by manucorporat** [comment]
Wait! is there a editor hint?

**Comment by cunzaizhuyi** [comment]
yes, here is the snapshot

image

**Comment by manucorporat** [comment]
damn... idk, gonna think about this. it's good to keep `<title>` in the other component because it allow to acces the qwikcity state

**Pull request closed without merging**
