### PR TITLE
feat: allow recursive class definitions

### PR DESCRIPTION
**Pull request by wmertens**
+ merge class and className

This allows easy forwarding of class props.

# What is it?

- [x] Feature / enhancement

# Description

class and className now accept recursive objects and both are honored.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by wmertens** [comment]
I couldn't find a test for the non-SSR className merging but I did a search for className and I think I caught all uses.

**Comment by manucorporat** [comment]
This is looking good! we need to add some tests for the vdom render, maybe some e2e too (i guess we can do that one later)

**Comment by manucorporat** [comment]
Also, not sure i like the idea of merging className and class, it can explode in some many ways, like fine grained updates with signals

**Comment by wmertens** [comment]
@manucorporat can you give an example of what will break?

Also note that right now, class and className overwrite eachother, whichever is last wins, so I think that's worse.

**Pull request closed without merging**
