### PR TITLE
add fastify starter server

### PR DESCRIPTION
**Pull request by Mouvedia**
# What is it?

- [x] Feature / enhancement

# Description

This is a copy of starters/servers/express for Fastify.
I have replaced Express by it in the Todo starter as a test.
I have also run `build.cli`, `cli` and `cli.validate` successfully.

It's probably missing something to be usable right away, though.

# Use cases and why

- 1. I wanted to use Qwik on an existing project
- 2. the cli should offer more choices

# Checklist:

- [ ] My code follows the [developer guidelines of this project](../CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by manucorporat** [comment]
Looks good to me! ready to merge?

**Comment by mhevery** [comment]
@Mouvedia Friendly ping. Can we merge this in? Looks like it is failing lint.

**Comment by Mouvedia** [comment]
@mhevery 
> `Error:   61:3  error  Unexpected console statement  no-console`

[It's also in the express one](https://github.com/BuilderIO/qwik/blob/main/starters/servers/express/src/entry.express.tsx#L18), hence it should be safe.

**Comment by Mouvedia** [comment]
@manucorporat at the pace Qwik is going this PR will be incompatible once you decide to merge it.
Is there a problem with it?

**Comment by manucorporat** [comment]
The deployment apis has been changing a lot, now we are in a good spot, i would rather open a new PR, since unfortunately very little can be reused

**Comment by Mouvedia** [comment]
see #3282

**Pull request closed without merging**
