### PR TITLE
feat(styles): support :global and pseudo

### PR DESCRIPTION
**Pull request by youngboy**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

more details in discussion https://github.com/BuilderIO/qwik/discussions/1063

also fixes: https://github.com/BuilderIO/qwik/issues/1081

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](../CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by felixsanz** [comment]
Looks good, but I think it also needs a test like this:

```js
equal(scopeStylesheet('a > :global(b) > .c {}', 'ABC'), 'a.⭐️ABC > b > .c.⭐️ABC {}');
```

(global in the middle)

**Comment by youngboy** [comment]
> Looks good, but I think it also needs a test like this:
> 
> ```js
> equal(scopeStylesheet('a > :global(b) > .c {}', 'ABC'), 'a.⭐️ABC > b > .c.⭐️ABC {}');
> ```
> 
> (global in the middle)

added 😅

**Comment by felixsanz** [comment]
I've tested this on my site and it works wonderfully! big thanks!

**Review by mhevery — APPROVED** [review]

**Review by felixsanz — APPROVED** [review]
Tested and working great!

**Pull request closed without merging**
