### PR TITLE
docs: add a new blog site powered by qwik

### PR DESCRIPTION
**Pull request by suhastgit**
Add a SSG blog built using qwik to the showcase.

The site is statically generated blog, features home page, blog pages, along with home pages for blogs listing all articles, routing on individual pages to next available article and practices good SEO techniques.

# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests / types / typos

# Description

Add a SSG blog built using qwik to the showcase hosted at https:// itbusinesshub.com.

# Use cases and why

-  The site is statically generated blog, and showcases features such as home page, blog pages, individual category pages for blogs listing all articles within the category, routing to next or previous post on individual blog post pages and has implemented good SEO techniques.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by zanettin** [comment]
thx @suhastgit for resubmitting the page 🙏 can you pls adjust the json (comma mismatch 👼 )
and it would be nice to analyze the PSI performance score for mobile devices (https://pagespeed.web.dev/analysis/https-itbusinesshub-com/1axjlmlf7k?form_factor=mobile) and see where u could improve. would love to merge it when the score is above 85 🙏  thanks again!

**Comment by suhastgit** [comment]
> thx @suhastgit for resubmitting the page 🙏 can you pls adjust the json (comma mismatch 👼 )
> and it would be nice to analyze the PSI performance score for mobile devices (https://pagespeed.web.dev/analysis/https-itbusinesshub-com/1axjlmlf7k?form_factor=mobile) and see where u could improve. would love to merge it when the score is above 85 🙏 thanks again!

My apologies for the comma mismatch @zanettin. That's now fixed. 

And thank you for pushing it harder, I have improved the performance as well. :) (https://pagespeed.web.dev/analysis/https-itbusinesshub-com/3kwr78wik3?form_factor=mobile) Please do let me know, should you need any more corrections. Thank you again , for considering the site for showcase.

**Comment by suhastgit** [comment]
Resubmitting the PR for integration of the site to showcase. Thanks

**Review by zanettin — APPROVED** [review]
looks great 🎉

**Pull request merged**
