### PR TITLE
docs: add link to official docs in readme

### PR DESCRIPTION
**Pull request by yjaaidi**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [X] Docs / tests

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](../CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
Please fix the missing new line, or just run `yarn lint`

**Comment by yjaaidi** [comment]
Done! Sorry I edited the file directly on github initially 😅

**Comment by shairez** [comment]
Great minds think alike @yjaaidi 😛😅

(didn't see you already did this)
https://github.com/BuilderIO/qwik/pull/661

**Comment by yjaaidi** [comment]
👯‍♂️😂

**Comment by shairez** [comment]
btw @mhevery - `yarn lint` didn't auto-fix it for me... I needed to do `prettier --write README.md` to have it fix

**Pull request merged**
