### PR TITLE
feat: initial preact support

### PR DESCRIPTION
**Pull request by heinthanth**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

Add Preact Integration for Qwik just like React. This will fulfill this feature request https://github.com/builderIO/qwik/issues/2328.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by zanettin** [comment]
Hi @heinthanth 👋 
Thanks a lot that you take the time to work on the initial support for preact 🙏 🎉 ! wanted to ask, what the current state of this PR is 👼 Thanks again

**Comment by heinthanth** [comment]
@zanettin I've implemented Preact as the same logic as React adapter. And example works well!

**Comment by zanettin** [comment]
Hi @heinthanth . That's amazing! I'll hand this changes over to @manucorporat then 😄 
Thank you very very much for doing that work! really appreciated! 🙏

**Comment by mhevery** [comment]
Hey @heinthanth , this is a fantastic piece of work! Thank you!

We are figuring out the best way to integrate this and get it into the hands of our users. We have some ideas and we would like to hear your thoughts.

## Option 1: Merge this into our mono repo
As you can imagine merging things into our mono repo has to meet a very high bar:
- It has to be production ready. Now that we have announced v1.0 we have to be sure that what goes in is of sufficient high quality.
- The implication of the above is that we are now on the hook to maintain that code. We may not be the right experts for maintaining it. Issues will be filed against our repo, and we may not be the best people to fix this issue.
- We don't think this is scalable because we can imagine a world where many people will want to add many features to our monorepo, and we would be on the hook to maintain it. A more distributed way of doing this would be better. 

## Option 2: Merge this into Qwik Labs

- This would be better as it would mean that we don't have to worry that it is of v1.0 quality.
- However, it still means that we would be on the hook to maintain the code. Issues would be field with us etc...

## Option 3: Have a community organization
- Have a https://github.com/QwikDev organization that can publish to `@qwikdev/____` The nice part of the org is that it still has the "seal" of Qwik without passing on the cost to the Qwik core maintainers. 
- This way, the core Qwik team is not on the hook to support the feature long time (as most of the time, they are not the experts)
- Qwik core team is not involved in having to review the PR and make a judgment call if the quality is good enough (given that hey are not the experts in that area)

---

Would love to hear your thoughts.

**Comment by heinthanth** [comment]
Hi @mhevery, personally, I think option 3 is the best. So that we can separate issues, PR in a separate repo and this won’t affect Qwik core quality.

**Comment by mhevery** [comment]
Great, let me know what repo name you would like and I can create one for you.

**Comment by heinthanth** [comment]
@mhevery how about `qwik-preact`? I think since we have `qwik-react`, `qwik-preact` is also a good name.

**Comment by mhevery** [comment]
Great you are now a new owner of https://github.com/QwikDev/qwik-preact. Let me know when you need to publish it to NPM under `@qwikdev/qwik-preact` and I will give you those rights as well.

**Comment by heinthanth** [comment]
Sure! I'll prepare and let you know once it's ready for experimental use!

**Comment by mhevery** [comment]
thanks for being awesome!

**Comment by heinthanth** [comment]
Hi @mhevery, I pushed my work here ( https://github.com/QwikDev/qwik-preact ) and I think it's ready to publish it.

**Comment by mhevery** [comment]
What is your NPM account handle?

— Misko
________________________________

**Comment by heinthanth** [comment]
It's @heinthanth

**Comment by mhevery** [comment]
Ok you should be ready to go.

**Comment by heinthanth** [comment]
@mhevery I think we can close this pull request in favor of https://www.npmjs.com/package/@qwikdev/qwik-preact

**Pull request closed without merging**
