### PR TITLE
docs: added useOn hooks

### PR DESCRIPTION
**Pull request by the-r3aper7**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

This should solve #2282 

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by shairez** [comment]
I think this should be part of the "Lifecycle" page no?

Maybe we should rename it in the menu to "Lifecycle (hooks)" to make it clearer

**Comment by the-r3aper7** [comment]
cool I will make the changes by tonight.

**Comment by shairez** [comment]
thanks buddy!

**Comment by shairez** [comment]
on second thought - not sure it's related to lifecycle
it looks like utils for adding event listeners in general

@manucorporat WDYT?

**Comment by manucorporat** [comment]
wondering if this is events

**Comment by manucorporat** [comment]
for me this are just events, in fact it's the same as doing: `<div onClick`, but programatically, so it can be composed with hooks

**Comment by the-r3aper7** [comment]
so, where should we add this?

**Comment by the-r3aper7** [comment]
@shairez  @manucorporat i have made the changes see it's matches the context of events page.

**Comment by zanettin** [comment]
@manucorporat  @shairez just tested the changes locally and they LGTM 👍 thanks a lot @the-r3aper7 🙏  hope we get this merged soon since it is a great addition for the docs imo.

**Comment by shairez** [comment]
thanks @the-r3aper7 and @zanettin !
merging

**Pull request merged**
