### PR TITLE
Reorganize .gitignore

### PR DESCRIPTION
**Pull request by szepeviktor**
# Overview

Organize git ignores in to categories.

[_source_](https://github.com/szepeviktor/debian-server-tools/blob/9abca88bda2b3805a7be0c9a535966d775da8d5f/.gitignore#L6-L12)

I'm highly unsure whether anchoring is correct and I've put ignores in the correct category.
Mainly in case of `/target/` and `**/server/`
Please help me.

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests / types / typos

# Description

We could provide example `~/.gitignore` contents in CONTRIBUTING.md

```gitignore
# OS
.DS_Store
Thumbs.db

# IDE and local environment
/.history/
/.idea/
*. or .* ?
```

This is because one project cannot cover every OS, every IDE, every local env.
Please see https://git-scm.com/docs/gitignore

### CODE REVIEW

**Comment by manucorporat** [comment]
I like the change, started to become a bit messy

**Comment by szepeviktor** [comment]
You're welcome.

It made the write a mini howto.

**Comment by zanettin** [comment]
looks like nested `/node_modules` and `dist` dirs are no longer excluded 😅  guess we should adjust that asap 😄 thanks for the cleanup @szepeviktor 🙏

**Comment by szepeviktor** [comment]
> nested `/node_modules` and `dist` dirs

Actually I've felt a contradiction.
This gitignore file is for Qwik development and qwik-app development too. Am I right?

**Comment by szepeviktor** [comment]
```gitignore
node_modules/
# and
dist/
```
No anchors.

**Comment by zanettin** [comment]
the issue i just faced after pulling the changes in was, that all pnpm workspaces (`packages/xxx`) `node_modules` and `dist` folders where tracked 😅

**Pull request merged**
