### PR TITLE
feat: server actions

### PR DESCRIPTION
**Pull request by manucorporat**
fixes https://github.com/BuilderIO/qwik/issues/2324
fixes https://github.com/BuilderIO/qwik/issues/2397
fixes https://github.com/BuilderIO/qwik/issues/2378
fixes https://github.com/BuilderIO/qwik/issues/2347
fixes https://github.com/BuilderIO/qwik/issues/2216
fixes https://github.com/BuilderIO/qwik/issues/1553
fixes https://github.com/BuilderIO/qwik/issues/1494
fixes https://github.com/BuilderIO/qwik/issues/1477
fixes https://github.com/BuilderIO/qwik/issues/2018
fixes https://github.com/BuilderIO/qwik/issues/2013

# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Todo

- [x] `serverAction$`
- [x] `serverAction$ FORM`
- [x] Test SPA navigation
- [x] Location.isLoading
- [x] API to refresh page (useNavigate?)
- [x] Disable returning data from onGet
- [x] onRequest always runs
- [x] Add response methods `sendText()` `sendJSON()` `sendData()`
- [x] Implement serverAction handling
- [x] Access loader data from `head` and other loaders
- [x] Access loader data from other loaders
- [x] Access action data from other loaders
- [ ] Future-proof integration with validation and type-checked routes
- [x] Vite 4
- [x] Replace node-fetch with undici
- [x] Test/update all integrations (specially forms)
- [ ] Cleanup
- [x] Multiple onGet/onRequest per layout
- [x] Ensure abort() stops per callback
- [x] Delete error reporting to Vite during endpoint crash

### CODE REVIEW

**Comment by the-zimmermann** [comment]
@manucorporat is this open task about the routing and something like that:

```ts
Server code runs on SPA navigation:

```ts
export const onGet: RequestHandler<Product | null> = async ({ params }) => {
  return fetchPrismaProduct(params.variantNumber);
};

export default component$(() => {

  const product = useEndpoint<Product | null>();

 return product?.name

}

```
Because using useNavigate or Link is causing prisma to run on the client, which is not expected reading the docs.
If not let me know, I can't find a specific issue about it and would present a test repo with prisma seeded.

Thanks in advance

**Comment by manucorporat** [comment]
with new api it would be:
```tsx
export const getProducts = loader$(({ params }) => {
  return fetchPrismaProduct(params.variantNumber);
});

export default component$(() => {

  const product = getProducts.use();

 return product.value.name
}
```

**Comment by jwickers** [comment]
FYI I think I found a bug in the spa navigation with this, if you follow a link to the same page with a different query params (?foo=bar) then it seems the last action reruns.

**Comment by DeVoresyah** [comment]
when this PR can be release? cuz I really need this fixed version to solve multiple `onGet` for layout and route. Refer to #2324

**Comment by Nefcanto** [comment]
@manucorporat thank you. This is an extremely useful feature. Can we access HTTP Request data in loaders (server actions)? Also, can we call loaders inside layouts?

**Pull request merged**
