### PR TITLE
feat: vue integration [WIP]

### PR DESCRIPTION
**Pull request by DominusKelvin**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

Adds the qwik-vue package for using Vue components in a Qwik applications

# Use cases and why

See docs for QwikReact

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by manucorporat** [comment]
Amazing!

**Comment by zanettin** [comment]
Hey @DominusKelvin 👋 
Hope you're doing well! Just wanted to quickly ask what the state and plan with this PR is 👼 can you give a short update? thanks a lot for your time and effort 🙏

**Comment by shairez** [comment]
@mhevery do we have a place for this in the qwikdev repo?

**Comment by mhevery** [comment]
> @mhevery do we have a place for this in the qwikdev repo?

Happy to create one. Need name and who the owner should be.

PS: @shairez I gave you rights to the repo so you should be able to create these as well.

**Comment by gioboa** [comment]
hi @DominusKelvin thanks for your commitment and for this amazing piece of work.

The best option for this kind of integration is:

---
## Have a community organization
- Have a https://github.com/QwikDev organization that can publish to `@qwikdev/____` The nice part of the org is that it still has the "seal" of Qwik without passing on the cost to the Qwik core maintainers. 
- This way, the core Qwik team is not on the hook to support the feature long time (as most of the time, they are not the experts)
- Qwik core team is not involved in having to review the PR and make a judgment call if the quality is good enough (given that hey are not the experts in that area)

---

I will close this PR, thanks again for your awesome job.

**Pull request closed without merging**
