### PR TITLE
docs: Add the first YouTube Tutorial in Portuguese about Qwik

### PR DESCRIPTION
**Pull request by LuisFilipePedroso**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by manucorporat** [comment]
Happy to add it, mind adding it to the end of the list instead?

**Comment by LuisFilipePedroso** [comment]
> Happy to add it, mind adding it to the end of the list instead?

Done!

**Comment by shairez** [comment]
thanks @LuisFilipePedroso 
There seem to be a prettier error in the page

Can you run and fix the prettier issues on just that page and commit+push please?

Thanks!

**Comment by LuisFilipePedroso** [comment]
cc @shairez could you run the workflows? 
I tried to fix

**Comment by shairez** [comment]
Thanks @LuisFilipePedroso !
merging

**Pull request merged**
