### PR TITLE
refactor(create-qwik): enhanced create qwik cli

### PR DESCRIPTION
**Pull request by zanettin**
# What is it?
- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description
Updated the `create-qwik` CLI to give it a bit fresher look'n'feel.
Let me know what you think about it.

## Before
Bildschirmfoto 2023-02-15 um 22 58 14

## After
Bildschirmfoto 2023-02-15 um 23 03 44

## Flow
https://user-images.githubusercontent.com/3241476/219188336-c379d3bd-403a-4c45-bcb6-6d9a3a6041d0.mp4

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

# Todos:
some gathered feedback:
- [ ] use custom styles to avoid the dim effect on the results
- [ ] re-align emojis (white, magenta, blue colors)
- [ ] change the end of the sequence and put `happy coding` into the results box

# Follow-up:
- [ ] refactor the qwik-cli
- [ ] update ASCII logo
- [ ] try to get `gradient-string` woking on CJS envs

### CODE REVIEW

**Comment by adamdbradley** [comment]
I. Love. It.

**Comment by hamatoyogi** [comment]
Holy cow @zanettin !
How did you create the Qwik logo ascii?
Love it!

**Comment by zanettin** [comment]
@hamatoyogi
thanks for your feedback 🙏 

> How did you create the Qwik logo ascii?
credits to @n8sabes and @KenAKAFrosty ❤️ they sent me several versions. the current one is generated with this tool https://ascii-generator.site/

**Comment by zanettin** [comment]
@adamdbradley this is the latest versions 😄 

Bildschirmfoto 2023-02-16 um 12 35 11

**Pull request merged**
