### PR TITLE
chore: make statement smooth

### PR DESCRIPTION
**Pull request by cunzaizhuyi**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

chore: make statement smooth

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by cunzaizhuyi** [comment]
Is it my fault of ci failed？ I just delete two words😄😃😄😇

**Comment by zanettin** [comment]
what have you done @cunzaizhuyi ?! 🤣 can you push en empty commit? `git commit --allow-empty` to re-start the CI pls? 🙏

**Comment by cunzaizhuyi** [comment]
> what have you done @cunzaizhuyi ?! 🤣 can you push en empty commit? `git commit --allow-empty` to re-start the CI pls? 🙏 

It works😃😃😃。

**Comment by adamdbradley** [comment]
thanks

**Pull request merged**
