### PR TITLE
deps(qwik-auth): update @auth/core

### PR DESCRIPTION
**Pull request by ulic75**

### CODE REVIEW

**Comment by ulic75** [comment]
Pfft, I don't know.  Hopefully someone can update the @auth/core version.

**Comment by shairez** [comment]
what happened @ulic75 ?

**Comment by ulic75** [comment]
> what happened @ulic75 ?

Oh, just the failed build stuff.  I thought it might be easy to slap the new version in there, but I guess not and don't have the time right now to sort it out.  And I'd rather not leave the dangling PR, there's enough danglers already :)

**Comment by shairez** [comment]
OK cool, thanks for the info
is there an issue opened about it?

**Comment by ulic75** [comment]
I don't think so. But @auth/core is still pre 1.0 so it's changing weekly.
Nothing that breaks qwik-auth so far though.

**Comment by shairez** [comment]
OK Cool thanks!

**Pull request closed without merging**
