### PR TITLE
fix(labs): filter out (group layouts)

### PR DESCRIPTION
**Pull request by uceumice**
# Overview

# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests / types / typos

# Description

The change omits pathless routes aka. group layout segments from the `path -> route` mapping.

# Use cases and why

Actual: `/some/(grouped)/route/index.tsx` -> `/some/(grouped)/route/` 
Expected: `/some/(grouped)/route/index.tsx` -> `/some/route/` 

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by uceumice** [comment]
I cannot get Qwik Repo (neither in Dev Containers nor on my machine) to run `ftm` without polluting each and every file with invisible (suspected EOL) changes.

**Review by mhevery — APPROVED** [review]
Thank you ❤️

**Comment by mhevery** [comment]
I see you are using qwik-types, I would love to get your feedback.

**Comment by mhevery** [comment]
I see there is a linting error, and I can't push a fix to your repo. So I have created a second PR with the change https://github.com/BuilderIO/qwik/pull/5171 and will close this one in favor of that ano. Thanks again...

**Comment by uceumice** [comment]
> I see you are using qwik-types, I would love to get your feedback.



> I see there is a linting error, and I can't push a fix to your repo. So I have created a second PR with the change #5171 and will close this one in favor of that ano. Thanks again...

Thank you, I am very excited to make some contributions to the project. I previously had experience with a similar feature written for *Remix Run*, so it naturally makes me a little bit curious. 

P.S.: After figuring out of how to `ftm` on Windows without sideeffects.

**Pull request closed without merging**
