### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by igorbabko**
# Overview

n/a

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests / types / typos

# Description

Fixed several typos on docs pages.

# Use cases and why

n/a

# Checklist:

n/a

### CODE REVIEW

**Comment by gioboa** [comment]
Hi, thanks for your contribution, please change the PR title to be compliant with the repo rules.

**Comment by igorbabko** [comment]
Hi, you are welcome!

Does it look good now?

**Review by mhevery — COMMENTED** [review]
WOW, thank you! ❤️

**Comment by gioboa** [comment]
> Hi, you are welcome!
> 
> Does it look good now?

Yep, thanks ❤️

**Pull request merged**
