### PR TITLE
fix: Uppercase handling for SameSite cookie values

### PR DESCRIPTION
**Pull request by ksjogo**
# Overview

Currently setting a SameSite value in the auth.js config with qwik-auth like this :
```
  cookies: {
      sessionToken: {
        name: 'authjs.session-token',
        options: {
          sameSite: true,
          secure: true,
          httpOnly: true,
          path: '/',
        },
      },
    },
 ```
 is broken.
 auth.js will internally have used the cookie library to convert these to uppercase already:

 https://github.com/jshttp/cookie/blob/38323bad3aa04bce840103ff6075bc05cc0bf884/index.js#L199

 So the header arriving in qwik-auth at fixCookies will have the uppercase version.
 
https://github.com/BuilderIO/qwik/blob/08a93f3846db156fc6c5278e9498d4feba73ad8e/packages/qwik-auth/src/index.ts#L161

 That uppercase version then is passed into qwik-city's req.cookie.set, which only treats lowercase SameSite correctly as of now.

# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests / types / typos

# Description

Introduce uppercase handling as well (to not break exisiting behaviour).

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by ksjogo** [comment]
@gioboa who could review this?

**Comment by wmertens** [comment]
Seems ok to me but I wonder, are the lowercase options even valid? Are mixed case options valid?

If only the capitalized versions are valid, perhaps it's best to mark the lowercase versions `/** @deprecated Use capitalized value */`?

**Comment by wmertens** [comment]
@ksjogo do you know that a unit test is failing?

**Comment by ksjogo** [comment]
> @ksjogo do you know that a unit test is failing?

They didn't ran automatically, didn't see it. Will fix them.

**Comment by ksjogo** [comment]
Should be fixed now.

**Comment by wmertens** [comment]
@ksjogo can you rebase and run `pnpm api.update`?

**Comment by ksjogo** [comment]
> @ksjogo can you rebase and run `pnpm api.update`?

Ok, pushing.

**Review by wmertens — APPROVED** [review]
LGTM

**Comment by ksjogo** [comment]
Cool, thanks for merging it.
@wmertens could you maybe also have a look at https://github.com/BuilderIO/qwik/pull/5602
It's another cookie issue with qwik-auth.

**Pull request merged**
