### PR TITLE
Add support for server$ cancelation using AbortSignal

### PR DESCRIPTION
**Pull request by DanielAdolfsson**
# Overview

When using `yield` in a server function, it makes no sense that it will continue even after the client connection has ended. In addition, I found that I needed to be able to cancel long running server functions from the client-side somehow. 
This PR adds support for passing an AbortSignal object when calling the server function.

This is not a complete PR yet, I merely want to check the temperature and see if this is an acceptable addition to the framework. The code works now, but only tested with the dev server.

# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

This PR introduces a couple of changes:
1. It adds a second signature to the QRL interface; to allow passing an AbortSignal object as a first argument to the server function.
2. Amends `serverQrl` to allow passing an AbortSignal - in which case it will be handed over to `fetch`. In essence, this just terminates the connection to the server.
4. Fixes the node middleware to ensure the writable stream is closed when the connection is closed.

# Use cases and why

I wanted to stream OpenAI generated text to the client by yielding new tokens. But quickly noticed that the server function would continue yielding tokens- even after leaving the page. This could be solved with a dedicated route, but I think being able to cancel long running server functions is not an outlandish idea.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by manucorporat** [comment]
This is amazing!

**Comment by DanielAdolfsson** [comment]
Might have been a little premature to merge it immediately, I haven't checked that I haven't broken anything. I'll do some more checking now then!

**Comment by amit13k** [comment]
Thanks a lot for for merging this feature. I just tried using this with an AbortSignal.Timeout. After abort, I get "Uncaught (in promise)". It seems there is no way to properly handle that exception. Any suggestions on how to fix this ?

**Comment by DanielAdolfsson** [comment]
You mean on the client side?

**Comment by amitkarmakar13** [comment]
> You mean on the client side?
I tried this example,
https://stackblitz.com/edit/qwik-starter-6ajbb2?file=src%2Froutes%2Findex.tsx

I can seeing this in console, https://cdn.discordapp.com/attachments/1105635284781117532/1108622570170888274/image.png

**Comment by DanielAdolfsson** [comment]
PR #4254 should fix this problem

**Comment by DanielAdolfsson** [comment]
I think that's a good idea, actually.

**Pull request merged**
