### PR TITLE
refactor(core): change `createContext` to `createContextId`

### PR DESCRIPTION
**Pull request by shairez**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

See #2859

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by shairez** [comment]
@manucorporat I ran `pnpm api.update` locally and committed the api updates as part of this commit as you can see here -
https://github.com/BuilderIO/qwik/pull/2898/files#diff-d787ac612834085c74cc96707b2caf420cf055c077114bfe5b762b0c762a8e13

not sure why it's failing on this again 🤷‍♂️

**Comment by manucorporat** [comment]
might need `pnpm build.full` to solve CI issues!

**Review by manucorporat — CHANGES_REQUESTED** [review]
- In order to be mergeable, we still need to export `createContext` with a `@deprecated` message, so we dont break all existing code.
- The docs changes should be done in another PR for because otherwise we will deploy the docs before the change in deployed, and because the docs will not build, since it's still using an older version
- Still need to find consensus if we want to go with a change
- If `createTokenId` is the option
-

**Comment by shairez** [comment]
@manucorporat thanks for the list - 

Item 1 is already done - 
https://github.com/BuilderIO/qwik/pull/2898/files#diff-dc3eff7507171fa2f19142e0aeb78326ffdc94263b837074a3f9c00859531cc3R71

https://github.com/BuilderIO/qwik/pull/2898/files#diff-fe2ee256fac7f0816adcdc712387674631c5a7de6871fbe81cdb469d2b9e9aaaR139

about the rest of the points - 
I'll move the docs to a separate PR but I've already invested 1.5h into this PR (trying to deal with all the build issues)
so let's first agree that this is a good change and then I'll invest more time into fixing all the issues, cool?

BTW, how does the process of finding consensus work? what are the next steps?

**Comment by zanettin** [comment]
@shairez just had the same issue with my pr regarding `api.update`. as stated by Manu, a `pnpm build.full && pnpm api.update` solved it 👍 and thx for the changes 😍

**Comment by shairez** [comment]
just finished installing everything locally

I ran `pnmp build.full` - and it was successful but no new files were generated as a result

Not sure how to proceed...

I'll try to close and re-open to trigger build again, let's see if that works...

**Comment by shairez** [comment]
Now the error is different.

It's like it's not running the build task on the right files for some reason 
look at the error message... 

```
Error: starters/apps/e2e/src/components/context/context.tsx(224,25): error TS2552: Cannot find name 'createContext'. Did you mean 'createContextId'?
Error: starters/apps/e2e/src/components/context/context.tsx(256,48): error TS2339: Property 'foo' does not exist on type 'object'.
```

This is clearly not the content of the actual file (at least not the one I pushed)

@manucorporat 

1. I don't know how to fix this CI build errors

2. how about I'd change the returned type `Context` to `ContextId`?

**Comment by manucorporat** [comment]
Go for it! Context to ContextID

also, make sure you do: `pnpm api.update`

**Comment by shairez** [comment]
@manucorporat done!

Can you please check this PR locally and run `pnpm build.full` and see if I'm crazy or does it work locally but not on CI?

**Review by manucorporat — APPROVED** [review]

**Comment by shairez** [comment]
as a lesson from this build issus on CI, I've added a "troubleshooting" section to `CONTRIBUTING.md` -

https://github.com/BuilderIO/qwik/pull/2946

**Pull request merged**
