### PR TITLE
docs: Add upester to the Showcase

### PR DESCRIPTION
**Pull request by tgv1975**
This PR adds upester to the Showcase of apps built with Qwik.

The upester app was initially built with Angular, then we decided to port it to Qwik for the superior SSR/SSG capabilities. It's been fun and educational, and upester is now 100% Qwik.

A big "Thank you!" to the Qwik maintainers!

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

Asking to add upester to the Showcase of apps made with Qwik.

# Use cases and why

No particular use case. If accepted, upester will be featured on the Showcase page.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [n/a] I have made corresponding changes to the documentation
- [n/a] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by tgv1975** [comment]
> Hi @tgv1975 👋 Thanks a lot for submitting this page and for the kind words ❤️ On the showcase screen we measure the mobile scores of all apps. On the submitted app the performance score is atm at [69](https://pagespeed.web.dev/analysis/https-upester-com/efzhjkwdwg?form_factor=mobile) which is good but also not great 👼 i've quickly analyzed the page and maybe you can already improve the score by limiting the things you want to use from bootstrap or follow the [best practices](https://getbootstrap.com/docs/5.0/customize/optimize/). hope that pushes the perf even further 🚀

Thanks for considering this! I've tested on my browser and got good scores, otherwise wouldn't have presumed to submit the app.

Here are my Lighthouse results on an fresh incognito window.

Mobile (browser emulation):

image

Desktop:

image

That aside, you're, of course, absolutely right about the optimization opportunities. I'll use pagespeed.web.dev as the benchmark, optimize on my side, and come back here when it's done, if you don't mind.

Thanks again!

**Comment by tgv1975** [comment]
We've optimized the app, and now we get [these scores](https://pagespeed.web.dev/analysis/https-upester-com/307u44ov75?form_factor=mobile):

image

@zanettin Can this be re-assessed?

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
Sorry about this, I have merged this accidentally. I have reverted the merge. My apologies.

**Comment by tgv1975** [comment]
@zanettin  This PR is now closed as merged, but the change has been reverted, and our app hasn't been added to the Showcase. Not sure what the final outcome of this PR should be. Should I reopen  the PR, or create a new one?

**Pull request merged**
