### PR TITLE
refactor(qwik): add css properties to jsx html attributes

### PR DESCRIPTION
**Pull request by huijiewei**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

add css properties to jsx html attributes.

# Use cases and why

none

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by manucorporat** [comment]
Adding a new dependency is not an easy decision for us, happy to add this functionality, but i would like to avoid the extra dependency

**Comment by huijiewei** [comment]
> Adding a new dependency is not an easy decision for us, happy to add this functionality, but i would like to avoid the extra dependency

css-type only typescript type define.

```
import type * as csstype from 'csstype';
```

dist will drop all.

**Comment by gioboa** [comment]
@huijiewei thanks for your help. `csstype` is a dependency in our codebase right now. The PR is old and there are few conflicts to solve, the best way to proceed is to create a new fresh PR with the latest codebase. 
Are you still interested in it?

**Comment by mhevery** [comment]
Thank you for your contribution. I am going to close this as a similar PR https://github.com/BuilderIO/qwik/pull/4577 has already landed and has added this dependency.

**Pull request closed without merging**
