### PR TITLE
docs: add page to showcase

### PR DESCRIPTION
**Pull request by Eucer**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by zanettin** [comment]
Hi @Eucer 
Is the URL a copy/past mistake? Should it be https://douvery-qwik.vercel.app/?

**Comment by Eucer** [comment]
Hi @zanettin , No, I want to show that part of the project, for now.

**Comment by zanettin** [comment]
Hi @Eucer 👋 

Sorry for the late reply. The scores are well but i am not sure if a single detail view should be listed or if we should wait, till you have more content on it. Personally I'd love to see an e-commerce site on the showcases 🙏 

Bildschirmfoto 2023-02-16 um 00 03 35

**Comment by Eucer** [comment]
@zanettin Hi , how are you ? I understand, it would be really good to publish it when it's finished, I still need to fix some things, thank you and I hope you're doing well!

**Comment by zanettin** [comment]
Hi @Eucer 👋 
Thanks for your reply! doing very good, thanks. hope you're fine as well?
Great to hear, that you're in the final steps with the project 🎉  I'll close this PR to keep a better overview of the tasks but please feel free to create a new one when ever you're ready ❤️ 
Looking forward to see it in full action 😄

**Pull request closed without merging**
