### PR TITLE
Ignore files in workspaces

### PR DESCRIPTION
**Pull request by szepeviktor**
Fix #4456

### CODE REVIEW

**Comment by zanettin** [comment]
thx 🙏  just created another [PR](https://github.com/BuilderIO/qwik/pull/4460) before 👼 guess we've accidentally deleted other ignores as well 🙈  (eg. `dist-dev`, `lib`, etc)

**Comment by szepeviktor** [comment]
It would be highly beneficial to ignore directories **where they really are**.
Where is `lib` created?

**Comment by zanettin** [comment]
totally with u 👍 since this would create many duplications i guess the core team thought this is the way they like to have it 😄 
to see where `lib` dirs are created run `pnpm run build` 👍

**Comment by zanettin** [comment]
Bildschirmfoto 2023-06-11 um 21 24 59

**Comment by szepeviktor** [comment]
Is it `/packages/*/lib/`?

**Pull request closed without merging**
