### PR TITLE
feat: ssr aws lambda apdapter

### PR DESCRIPTION
**Pull request by leifermendez**
# What is it?

New Adaptor for AWS Lamda 
https://share.vidyard.com/watch/yKuXu8uiPpgRqHopySs9Pe?
image

- [x ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description
New implementation for deploy qwik add easy

Example: https://rsltkw254b.execute-api.us-east-1.amazonaws.com/

# Checklist:

- [ x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ x] I have performed a self-review of my own code
- [ x] I have made corresponding changes to the documentation
- [x ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by leifermendez** [comment]
[serverles](https://github.com/leifermendez/serverless-plugin-qwik)

**Comment by adamdbradley** [comment]
We [just made an update](https://github.com/BuilderIO/qwik/pull/1805) to how servers/adaptors are imported from Qwik City projects. Would you be able to update this PR to the last structure updates? https://github.com/BuilderIO/qwik/tree/cdea8ff43b2f7f3eab1634c795e360c8a5ae7ec9/starters/adaptors/cloudflare-pages

This will be a great addition, thanks!

**Comment by leifermendez** [comment]
New structure applied @adamdbradley  also i removed somes dependencies and moved a logic part to other package for avoid mix stranger somethings here.

https://github.com/leifermendez/serverless-plugin-qwik

**Comment by adamdbradley** [comment]
Is this right for where the vite.config.ts file would go? `starters/adaptors/aws-lambda/adaptors/aws-lambda/vite.config.ts`

**Comment by leifermendez** [comment]
I need to review some files and make a test @adamdbradley I hope the next week launch an update

**Comment by zanettin** [comment]
Hi @leifermendez 👋 
Just scanning the open PRs and found this one 😄  a bit dusty but looks as good as new 🤣 what's the state of it?

**Comment by leifermendez** [comment]
> Hi @leifermendez 👋 Just scanning the open PRs and found this one 😄 a bit dusty but looks as good as new 🤣 what's the state of it?

🙌 Hi @zanettin I need check this again because I remember this I left as draft for something but I not exactly the cause

**Comment by zanettin** [comment]
@gioboa did i understand you right, that you have smth working in that regard?

**Comment by gioboa** [comment]
Yep, I have it with edge AWS lambda

**Comment by zanettin** [comment]
could we create a integration out of it? 😍

**Comment by gioboa** [comment]
Yes, that's the plan

**Comment by icarus-sullivan** [comment]
Bumping in excitement

**Pull request closed without merging**
