### PR TITLE
Rewrite get query logic

### PR DESCRIPTION
**Pull request by mmarkelov**
# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests

# Description

Please see #1746. 
There is a problem with current approach when we try to get array values, it will be always one single value. 
I'm not sure if it should handle this case, but if it should be fixed, I guess that there will be maybe some breaking changes(but not sure).
If you are ok with this solution, I could try to fix TS errors 

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by manucorporat** [comment]
I think this PR makes sense, only worried about the breaking change in terms of types and that now it’s not easy to easily get a query value because it’s always needed to handled the string or array of strings

**Comment by mmarkelov** [comment]
> I think this PR makes sense, only worried about the breaking change in terms of types and that now it’s not easy to easily get a query value because it’s always needed to handled the string or array of strings

Alternatively, it can be another way to handle. Keep it as the string, but if we got an array we can translate it string with join.
But IDK how we should parse it in `getPathnameForDynamicRoute` function

**Comment by tuurbo** [comment]
> I think this PR makes sense, only worried about the breaking change in terms of types and that now it’s not easy to easily get a query value because it’s always needed to handled the string or array of strings

Just a thought, but to keep the current simplicity of not having to handle a string or array of strings. Would something like this be possible? Call the query param as you currently do and return a string (current behavior). Call `.getAll('...')` and always return a array of strings.



URL: `example.com?brand=amd&brand=intel&category=cpu`

```ts
location.query.category // 'cpu'
location.query.getAll('category') // ['cpu']

location.query.brand // 'intel'
location.query.getAll('brand') // ['amd', 'intel']
```

--- OR ----

Support multiple ways to access the query params similar to Angular
```ts
location.query.category // 'cpu'
location.queryMap.get('category') // 'cpu'
location.queryMap.getAll('category') // ['cpu']

location.query.brand // 'intel'
location.queryMap.get('brand') // 'intel'
location.queryMap.getAll('brand') // ['amd', 'intel']
```

**Comment by mmarkelov** [comment]
@tuurbo I'm ok with your suggestions. I can implement this kind of logic

**Comment by tuurbo** [comment]
or here is an even simpler way the query could be accessed
```
// Always return string
location.query.brand // 'intel' 

// Always return string array
location.queryMap.brand // ['amd', 'intel']
```

what do you think @manucorporat  @mmarkelov ?

**Comment by manucorporat** [comment]
how about query and queryAll?
```
// Always return string
location.query.brand // 'intel' 

// Always return string array
location.queryAll.brand // ['amd', 'intel']
```

**Comment by tuurbo** [comment]
That works for me

**Comment by manucorporat** [comment]
however i dont like the idea what we have two root objects for the same concept, i can see developers getting confused... what if we just exposed directly the `URLSearchParams`?

It would require a little change in qwik to support serializing URLSearchParams, but should be possible!
and deprecate `query`

cc @adamdbradley

**Comment by zanettin** [comment]
Thanks a lot @mmarkelov for taking the time to create this PR 🙏  as @adamdbradley stated in the linked issue, this was fixes in https://github.com/BuilderIO/qwik/pull/2385. I'll therefore close this PR for now. Please feel free to open a new one if you see any further improvements in that or any other regard 🎉

**Pull request closed without merging**
