### PR TITLE
refactor(optimizer): remove using resolvePackageData API from Vite

### PR DESCRIPTION
**Pull request by bluwy**
# Overview

# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Remove `resolvePackageData` usage to use `findDepPkgJsonPath` from `vitefu` instead.

I'm not sure if my change is correct as I'm not sure of the use of `sys.strictDynamicImport` here. Let me know if I did something wrong!

# Use cases and why

Vite 5 is removing the `resolvePackageData` API to help improve future performance and bug fixes. (https://github.com/vitejs/vite/pull/14584) The API is not used widely so making a PR here to refactor it away.

I'm using [`vitefu`](https://github.com/svitejs/vitefu) which I maintain on the side and implements the same heuristic, and is also used by frameworks like Svelte, Solid, and Astro today.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by gioboa** [comment]
Thanks for your contribution, this PR needs a review from the core team.

**Review by mhevery — APPROVED** [review]
Thank you for the PR. This seems reasonable. Waiting for the tests to pass

**Comment by bluwy** [comment]
Seems like it has trouble bundling the library, I can check it later today.

**Comment by wmertens** [comment]
@bluwy it looks like vitefu is more precise about node versions, we're targeting at least 16.8 (and actually 16 just left LTS so maybe we should target 18)

**Comment by bluwy** [comment]
`vitefu` can work on node 16.8, it even supports Vite 3 so around node 14.8 is the minimum. I can make the build work locally by tweaking a few things:

1. Make this ESM build target node like CJS (`platform: 'node'`): https://github.com/BuilderIO/qwik/blob/6d0be5e2ba46dfbee76e11017abaa82124b65235/scripts/submodule-server.ts#L32
2. Make this ESM build also target node like CJS (`platform: 'node'`: https://github.com/BuilderIO/qwik/blob/6d0be5e2ba46dfbee76e11017abaa82124b65235/scripts/submodule-optimizer.ts#L41
3. Mark this as `node16.8`: https://github.com/BuilderIO/qwik/blob/6d0be5e2ba46dfbee76e11017abaa82124b65235/scripts/util.ts#L156
4. And remove the TLA in https://github.com/svitejs/vitefu/blob/d8d82fa121e3b2215ba437107093c77bde51b63b/src/index.js#L15

But I'm not really sure if no1-3 are safe changes for qwik currently. Or maybe something you'd want to do a later time when supporting Vite 5?

I can definitely refactor away the TLA for no4 if needed, but if there's a "bigger picture" refactor to be done for the build pipeline (especially that Vite 5 will deprecate it CJS node api), then maybe this is something you'll want to hold on till a later stage to fix.

**Comment by mhevery** [comment]
> But I'm not really sure if no1-3 are safe changes for qwik currently. Or maybe something you'd want to do a later time when supporting Vite 5?

What specifically would this change do? How will the output be changed? Can you give it a try and see what happens to the build?

**Comment by bluwy** [comment]
Aight with a little grease I'm actually able to make it work without my mentioned changes above, except no2. [`6d91050` (#5312)](https://github.com/BuilderIO/qwik/pull/5312/commits/6d91050085b8a787a07ae4f5183d4b6993518280) shows the build change needed to make it work. I used an esbuild plugin to remove the TLA manually for now.

**Review by mhevery — APPROVED** [review]
Thank you for your contribution. ❤️

**Pull request merged**
