### PR TITLE
docs: Fix README badges

### PR DESCRIPTION
**Pull request by rerelurelu**
# Overview

スクリーンショット 2024-03-16 17 29 17

- Remove Vercel Server badge
- Add Vercel Serverless badge
- Add Vercel Edge budge

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests / types / typos

# Description

As mentioned Overview.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by gioboa** [comment]
I tested this change but it's showing "failing" :thinking: 

image

**Comment by rerelurelu** [comment]
> I tested this change but it's showing "failing" 

It's showing up because the [Vercel Edge](https://github.com/BuilderIO/qwik-city-e2e/actions/workflows/vercel-edge.yml) and [Vercel Serverless](https://github.com/BuilderIO/qwik-city-e2e/actions/workflows/vercel-serverless.yml) workflows are failing.
Neither of these errors is caused by this PR.

**Comment by wmertens** [comment]
Thanks! I don't suppose you can fix the workflows? ;-)

**Comment by wmertens** [comment]
So the serverless workflow fails here https://github.com/BuilderIO/qwik-city-e2e/actions/runs/8362101976/job/22891855652#step:8:26

and the edge workflow was disabled 8 months ago :thinking:

**Comment by wmertens** [comment]
ok the qwik-city branch of the workflows is behind, that's why. Added a PR

**Pull request merged**
