### PR TITLE
starter: Update deps and code of supabase auth helpers qwik pkg

### PR DESCRIPTION
**Pull request by diecodev**
This PR updates following deps to the latest version:
- @supabase/supabase-js
- @supabase/supabase-auth-helpers-shared
- @builder.io/qwik
- @builder.io/qwik-city

Also upgrade the pkg version to 0.1.0 based on [npm statements](https://docs.npmjs.com/about-semantic-versioning).

### CODE REVIEW

**Comment by diecodev** [comment]
@zanettin I just updated the branch to be up to date with the main branch. I hope this PR gets approved so that the package can be approved in the main supabase repo as well. I would also like to make some blog posts talking about this particular package, since I have read a lot of issues about it and I would like to help the community to clear some common doubts.

**Comment by zanettin** [comment]
thx again @diecodev 🙏 i am not familiar with subabase and trying to find smb using it to test these changes atm. sry for long review loop

**Comment by gioboa** [comment]
@zanettin I will test the implementation

**Comment by zanettin** [comment]
thx a lot @gioboa 🙏

**Comment by zanettin** [comment]
Hi @gioboa 
Thor was here for a visit and he borrowed me his 🔨 . Looks like `pnpm i && pnpm build` does work now 🤣  thanks again for your test 🙏

**Review by gioboa — APPROVED** [review]
It looks good to me. I tested the docs example with this new version and works like a charm.
Thanks @diecodev 🚀

**Pull request merged**
