### PR TITLE
modify the docs link 

### PR DESCRIPTION
**Pull request by ColynYu**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ x ] Docs / tests

# Description

modify the docs link that shows on terminal after `npm run qwik add express`

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by cunzaizhuyi** [comment]
thank you

**Comment by zanettin** [comment]
Hi @ColynYu 

Thank you very much for fixing them 🙏  There was just an issue created https://github.com/BuilderIO/qwik/issues/2505 where another domain was mentioned as well ( `adaptors/overview`). Would you like to fix this as well within your PR? otherwise i can create a new one for that case 👍  just let me know.

Thanks once again 🙏

**Comment by zanettin** [comment]
fixes #2502

**Comment by ColynYu** [comment]
I have fixed the issue #2505 you mentioned

**Comment by zanettin** [comment]
Woah great work! thanks a lot! hope smb with merging power can put that live soon 😄 @shairez @adamdbradley @manucorporat 🙏

**Comment by adamdbradley** [comment]
thanks for the update!

**Pull request merged**
