### PR TITLE
Docs: add partytown starter doc

### PR DESCRIPTION
**Pull request by leifermendez**
# What is it?
image

- [ ] Feature / enhancement
- [ ] Bug
- [x ] Docs / tests

# Description
Added new section for explained the difference starters scripts

# Checklist:

- [x ] My code follows the [developer guidelines of this project](../CONTRIBUTING.md)
- [ x] I have performed a self-review of my own code
- [x ] I have made corresponding changes to the documentation
- [x ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by shairez** [comment]
Thanks @leifermendez !

it seems like it's failing on the need to run `yarn api.update`

**Comment by leifermendez** [comment]
> Thanks @leifermendez !
> 
> it seems like it's failing on the need to run `yarn api.update`

Thanks I will do it

**Comment by leifermendez** [comment]
Done

**Comment by shairez** [comment]
Thanks @leifermendez 
Looking good brother!

I fixed some typos and rephrased some of the explanations on the doc

Going to merge it when all the checks will pass

Thanks again for the contribution! 🙏

**Comment by leifermendez** [comment]
> Thanks @leifermendez Looking good brother!
> 
> I fixed some typos and rephrased some of the explanations on the doc
> 
> Going to merge it when all the checks will pass
> 
> Thanks again for the contribution! 🙏

You're welcome 🤗. Let's go for more

**Pull request merged**
